function [data, auxData, metaData, txtData, weights] = mydata_Moloch_horridus
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Reptilia';
metaData.order      = 'Squamata';
metaData.family     = 'Agamidae';
metaData.species    = 'Moloch_horridus';
metaData.species_en = 'Thorny devil';

metaData.ecoCode.climate = {'BWh'};
metaData.ecoCode.ecozone = {'TA'};
metaData.ecoCode.habitat = {'0iTd'};
metaData.ecoCode.embryo  = {'Tt'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'0iO'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(25); % K, body temp

metaData.data_0     = {'ab'; 'ap'; 'am'; 'Lb'; 'Li';  'Ri'};
metaData.data_1     = {'t-L'; 'L-Ww'};

metaData.COMPLETE   = 2.7; % using criteria of LikaKear2011

metaData.author   = {'Bas Kooijman'};    
metaData.date_subm = [2023 01 03];              
metaData.email    = {'bas.kooijman@vu.nl'};            
metaData.address  = {'VU University, Amsterdam'};   

metaData.curator     = {'Starrlight Augustine'};
metaData.email_cur   = {'starrlight@tecnico.ulisboa.pt'}; 
metaData.date_acc    = [2023 01 03];

%% set zero-variate data
data.ab = 15*7; units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = 'Spor1955';
  temp.ab = C2K(27); units.temp.ab = 'K'; label.temp.ab = 'temperature';
  comment.ab = '13-18 w';
data.tp = 3*365; units.tp = 'd'; label.tp = 'time since birth at puberty'; bibkey.tp = 'Spor1965';
  temp.tp = C2K(25); units.temp.tp = 'K'; label.temp.tp = 'temperature';
data.am = 20*365; units.am = 'd'; label.am = 'life span'; bibkey.am = 'Spor1965';
  temp.am = C2K(25); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lb = 3.6; units.Lb = 'cm'; label.Lb = 'SVL at birth'; bibkey.Lb = 'Spor1955';
  comment.Lb = '6 cm total length, coverted to SVL';
data.Li = 11; units.Li = 'cm'; label.Li = 'ultimate SVL'; bibkey.Li = 'Spor1965';
  comment.Li = '18.8 cm total length, coverted to SVL';

data.Ri = 6.5/365; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = 'Spor1955';
  temp.Ri = C2K(25); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = '6-7 eggs per clutch, 1 clutch per yr';

%% set uni-variate data
% length-weight
data.LW_f = [ ... SVL (cm), weight (g)
5.435	10.411
5.705	10.052
6.001	12.373
6.001	11.225
6.799	16.397
6.927	20.491
7.094	22.546
7.493	20.284
8.212	35.656
8.610	43.090
8.611	32.883
8.621	52.022
8.907	36.353
8.919	42.351
8.931	48.731
9.031	65.199
9.085	50.658
9.201	50.668
9.315	63.692
9.394	49.791
9.395	43.157
9.418	62.042
9.472	48.267
9.521	63.454
9.523	50.313
9.700	72.018
9.703	50.838
9.768	47.016
9.769	42.423
9.885	41.922
9.911	40.011
9.998	55.202
10.009	69.238
10.191	58.025
10.204	60.067
10.255	63.644
10.292	70.282
10.614	68.268
10.833	68.032
10.909	76.459];
units.LW_f = {'cm', 'g'}; label.LW_f = {'SVL', 'wet weight','females'};
bibkey.LW_f = 'PianPian1970'; comment.LW_f = 'Data for females';
%
data.LW_m = [ ... SVL (cm), weight (g)
4.972	6.672
5.371	8.109
6.232	16.093
6.515	17.393
6.695	18.685
6.875	21.252
7.106	28.034
7.158	22.041
7.184	20.130
7.275	18.351
7.493	23.473
7.518	24.624
7.647	27.059
7.672	28.975
7.891	30.269
7.956	27.978
7.956	27.085
7.967	33.849
7.994	31.427
8.007	29.003
8.071	27.988
8.110	31.309
8.174	30.676
8.175	24.424
8.212	33.359
8.264	30.301
8.277	31.451
8.278	26.347
8.315	34.516
8.483	28.278
8.520	40.148
8.521	33.385
8.585	35.049
8.688	34.931
8.714	36.336
8.779	30.345
8.791	38.512
9.024	30.749
9.088	33.816
9.215	40.207
9.240	49.268
9.486	39.081
9.602	39.857];
units.LW_m = {'cm', 'g'}; label.LW_m = {'SVL', 'wet weight','males'};
bibkey.LW_m = 'PianPian1970'; comment.LW_m = 'Data for males';

% time-length
data.tL = [ ... % time since birth (yr), total length (cm): female, male
    0    6    6
    0.75 9.6  9.6
    1   11.5 11.5
    2   14.0 13.5 
    3   16.1 15.0
    4   17.2 15.7
    5   17.9 15.8
    7   18.3 16.2
    8   18.8 NaN];
data.tL(:,1) = data.tL(:,1)*365;
data.tL(:,2:3) = data.tL(:,2:3)*9/15; % convert total length to SVL
units.tL = {'d', 'cm'}; label.tL = {'time', 'SVL'};
temp.tL = C2K(25); units.temp.tL = 'K'; label.temp.tL = 'temperature';
bibkey.tL = {'Spor1955','Spor1965'}; treat.tL = {1, {'female','male'}};
comment.tL = 'Total length was converted to SVL by factor 9/15,  based on photo';

%% set weights for all real data
weights = setweights(data, []);
weights.tL = 10 * weights.tL;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);
weights.psd.v = 2 * weights.psd.v;

%% pack auxData and txtData for output
auxData.temp = temp;
auxData.treat = treat;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Group plots
set1 = {'LW_f','LW_m'}; subtitle1 = {'Data from females, males'};
metaData.grp.sets = {set1};
metaData.grp.subtitle = {subtitle1};

%% Discussion points
D1 = 'males are assumed to differ from females by {p_Am} only';
D2 = 'Temperature of 25C based on modelling using NicheMapR of bearded dragon body temperatures in the wild';
D3 = 'tp was ignorged because of large uncertainty, Wwp because of inconsistency with LWw data';
metaData.discussion = struct('D1',D1, 'D2',D2, 'D3',D3);

%% Facts
F1 = 'Specialized on feeding on the ant Iridomyrmes niger';
metaData.bibkey.F1 = 'PianPian1970'; 
metaData.facts = struct('F1',F1);

%% Links
metaData.links.id_CoL = '43WS4'; % Cat of Life
metaData.links.id_ITIS = '1055593'; % ITIS
metaData.links.id_EoL = '791432'; % Ency of Life
metaData.links.id_Wiki = 'Moloch_horridus'; % Wikipedia
metaData.links.id_ADW = 'Moloch_horridus'; % ADW
metaData.links.id_Taxo = '49207'; % Taxonomicon
metaData.links.id_WoRMS = ''; % WoRMS
metaData.links.id_ReptileDB = 'genus=Moloch&species=horridus'; % ReptileDB
metaData.links.id_AnAge = 'Pogona_barbata'; % AnAge


%% References
bibkey = 'Wiki'; type = 'Misc'; bib = ...
'howpublished = {\url{http://en.wikipedia.org/wiki/Moloch_horridus}}';
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'PianPian1970'; type = 'Article'; bib = [ ... 
'title = {The Ecology of \emph{Moloch horridus} ({L}acertilia: {A}gamidae) in {W}estern {A}ustralia}, '...
'volume = {1970(1)}, '...
'journal = {Copeia}, '...
'author = {Eric R. Pianka and Helen D. Pianka}, '...
'year = {1970}, '...
'pages = {90-103}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Spor1965'; type = 'Article'; bib = [ ... 
'title = {Additional observations on the life history of the mountain devil, \emph{Moloch horridus}, in captivity}, '...
'volume = {9}, '...
'journal = {Ibid}, '...
'author = {Sporn, C. C.}, '...
'year = {1965}, '...
'pages = {157-159}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Spor1955'; type = 'Article'; bib = [ ... 
'title = {THE BREEDING OF THE MOUNTAIN DEVIL IN CAPTIVITY}, '...
'volume = {5}, '...
'journal = {The Western Australian Naturalist}, '...
'author = {Sporn, C. C.}, '...
'year = {1955}, '...
'pages = {1-5}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
