function [prdData, info] = predict_Moloch_horridus(par, data, auxData)
% file generated by prt_predict

% unpack par, data, auxData
cPar = parscomp_st(par); vars_pull(par);
v2struct(par); v2struct(cPar); v2struct(data); v2struct(auxData);

% compute temperature correction factors
pars_T = T_A;
TC_am = tempcorr(temp.am, T_ref, pars_T);
TC_Ri = tempcorr(temp.Ri, T_ref, pars_T);
TC_ab = tempcorr(temp.ab, T_ref, pars_T);
TC_tp = tempcorr(temp.tp, T_ref, pars_T);
TC_tL = tempcorr(temp.tL, T_ref, pars_T);

% life cycle
pars_tp = [g k l_T v_Hb v_Hp];
[tau_p, tau_b, l_p, l_b, info] = get_tp(pars_tp, f);
if ~info; prdData = []; return; end

% birth
L_b = L_m * l_b;                  % cm, structural length at birth
a_b = tau_b/ k_M/ TC_ab;          % d, age at birth
Lw_b = L_b/ del_M;                % cm, physical length at birth
Ww_b = L_b^3 * (1 + f * ome);     % g, wet weight at birth

% puberty
L_p = L_m * l_p; % cm, structural length at puberty
t_p = (tau_p - tau_b)/ k_M/ TC_tp; % d, time since birth at puberty
Lw_p = L_p/ del_M; % cm, physical length at puberty
Ww_p = L_p^3 * (1 + f * ome); % g, wet weight at puberty

% ultimate
l_i = f - l_T; % -, scaled ultimate length
L_i = L_m * l_i; % cm, ultimate structural length
Lw_i = f * L_m/ del_M; % cm, ultimate physical length
Ww_i = L_i^3 * (1 + f * ome); % g, ultimate wet weight 

% reproduction
pars_R = [kap; kap_R; g; k_J; k_M; L_T; v; U_Hb; U_Hp]; % compose parameter vector
R_i = TC_Ri * reprod_rate(L_i, f, pars_R); % #/d, ultimate reproduction rate

% life span
pars_tm = [g; l_T; h_a/ k_M^2; s_G]; % compose parameter vector
tau_m = get_tm_s(pars_tm, f, l_b); % -, scaled mean life span
a_m = tau_m/ k_M/ TC_am; % d, mean life span

% males
p_Am_m = z_m * p_M/ kap;             % J/d.cm^2, {p_Am} spec assimilation flux
E_m_m = p_Am_m/ v;                   % J/cm^3, reserve capacity [E_m]
g_m = E_G/ (kap* E_m_m);             % -, energy investment ratio
m_Em_m = y_E_V * E_m_m/ E_G;         % mol/mol, reserve capacity 
w_m = m_Em_m * w_E/ w_V;             % -, contribution of reserve to weight
L_mm = v/ k_M/ g_m;                  % cm, max struct length
L_bm = l_b * L_mm; L_im = f * L_mm;  % cm, struct length, birth & ultimate
Ww_im = L_im^3 * (1 + f * w_m);      % g, ultimate wet weight

% pack to output
prdData.ab = a_b;
prdData.tp = t_p;
prdData.am = a_m;
prdData.Lb = Lw_b;
prdData.Li = Lw_i;
prdData.Ri = R_i;

% length - wet weight
EWw_f = (LW_f(:,1) * del_M).^3 * (1 + f_LW * w); % g, wet weight
EWw_m = (LW_m(:,1) * del_M).^3 * (1 + f_LW * w_m); % g, wet weight

% time - length
L_b = L_m * get_lb([g; k; v_Hb], f_tL); L_i = f_tL * L_m; % cm, structural lengths
r_B = TC_tL * k_M/ 3/ (1 + f_tL/ g); % 1/d, von Bertalanffy growth rate
L = L_i - (L_i - L_b) * exp( - r_B * tL(:,1)); % cm, structural length
ELw_f = L/ del_M; % cm, SVL
%
L_bm = L_mm * get_lb([g_m; k; v_Hb], f_tL); L_im = f_tL * L_mm; % cm, structural lengths
r_Bm = TC_tL * k_M/ 3/ (1 + f_tL/ g_m); % 1/d, von Bertalanffy growth rate
L = L_im - (L_im - L_bm) * exp( - r_Bm * tL(:,1)); % cm, structural length
ELw_m = L/ del_M; % cm, SVL


% pack to output
prdData.LW_f = EWw_f;
prdData.LW_m = EWw_m;
prdData.tL = [ELw_f ELw_m];

