function [data, auxData, metaData, txtData, weights] = mydata_Cottus_gobio
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Perciformes';
metaData.family     = 'Cottidae';
metaData.species    = 'Cottus_gobio';
metaData.species_en = 'European bullhead';

metaData.ecoCode.climate = {'Cfb','Dfd'};
metaData.ecoCode.ecozone = {'THp'};
metaData.ecoCode.habitat = {'0iFc','0iFr'};
metaData.ecoCode.embryo  = {'Fnm'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biCi'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(13); % K, body temp

metaData.data_0     = {'am','Lp','Li','Wwb','Wwi','Ri'};
metaData.data_1     = {'t-L','tL_m','tL_f'};

metaData.COMPLETE   = 2.5; % using criteria of LikaKear2011

metaData.author     = {'Bas Kooijman'};
metaData.date_subm  = [2020 8 25];
metaData.email      = {'bas.kooijman@vu.nl'};
metaData.address    = {'VU University, Amsterdam'};

metaData.author_mod_1   = {'Bas Kooijman'};    
metaData.date_mod_1     = [2023 04 07];              
metaData.email_mod_1    = {'bas.kooijman@vu.nl'};            
metaData.address_mod_1  = {'VU University, Amsterdam'};   

metaData.curator     = {'Starrlight Augustine'};
metaData.email_cur   = {'starrlight@tecnico.ulisboa.pt'}; 
metaData.date_acc    = [2023 04 07];

%% set zero-variate data
data.am = 3650; units.am = 'd'; label.am = 'life span'; bibkey.am = 'fishbase';
  temp.am = C2K(13); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lp = 4.2; units.Lp = 'cm'; label.Lp = 'total length at puberty for females'; bibkey.Lp = 'fishbase';
  comment.Lp = 'based on purberty in second yr and tL data';
data.Li = 18; units.Li = 'cm'; label.Li = 'ultimate total length for females'; bibkey.Li = 'fishbase';

data.Wwb = 8.2e-3; units.Wwb = 'g'; label.Wwb = 'wet weight at birth'; bibkey.Wwb = 'Pete2009';
  comment.Wwb = 'based on egg diameter of 2.5 mm for Cottus beldingii: pi/6*0.25^3';
data.Wwi = 90.5; units.Wwi = 'g'; label.Wwi = 'ultimate wet weight for females'; bibkey.Wwi = 'fishbase';
  comment.Wwi = 'based on 0.00977*Li^3.16, see F1';

data.Ri = 600/365; units.Ri = '#/d'; label.Ri = 'reproduction rate'; bibkey.Ri = 'fishbase';
  temp.Ri = C2K(13); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';

%% set uni-variate data
% time - length
data.tL_f = [ ... 
  466.78 7.107
  466.968 6.859
  514.633 6.967
  522.94 6.506
  660.442 7.079
  662.745 7.54
  734.74 7.046
  739.642 7.578
  796.843 9.104
  833.468 9.779
  833.71 9.46
  887.19 8.895
  892.334 9.108
  1022.28 9.149
  1035.41 9.326
  1098.37 10.25
  1098.53 10.038
  1164.77 10.147
  1201.2 11.069
  1246.65 10.61
  1246.89 10.291
  1249.7 10.079
  1257.18 10.717
  1312.64 11.038
  1384.63 10.545
  1386.88 11.077
  1463.54 11.434
  1619.42 12.255
  1630.11 12.149
  1762.76 12.119];
units.tL_f = {'d', 'cm'}; label.tL_f = {'time', 'length', 'female'};
temp.tL_f = C2K(13); units.temp.tL_f = 'K'; label.temp.tL_f = 'temperature';
bibkey.tL_f = 'Pete2009';
comment.tL_f = 'data for females';
%
data.tL_m = [ ... 
  126.858 4.116
  168.681 4.933
  221.329 5.467
  361.967 5.401
  434.519 7.673
  435.11 6.893
  440.818 6.361
  474.039 8.029
  516.399 8.137
  516.775 7.64
  667.271 8.568
  667.593 8.142
  731.093 8.358
  741.515 8.606
  803.753 10.487
  832.904 10.523
  893.993 10.42
  894.208 10.136
  1100.22 11.314
  1100.68 10.711
  1102.68 11.562
  1203.08 12.097
  1208.62 11.779
  1256.18 12.029
  1261.81 11.603
  1262 11.355
  1391.78 11.608
  1394.06 12.105
  1468.12 12.391
  1473.39 12.427
  1528.64 13.032
  1573.65 13.14
  1631.79 13.425
  1631.96 13.213
  1767.32 13.112];
units.tL_m = {'d', 'cm'}; label.tL_m = {'time', 'length', 'male'};
temp.tL_m = C2K(13); units.temp.tL_m = 'K'; label.temp.tL_m = 'temperature';
bibkey.tL_m = 'Pete2009';
comment.tL_m = 'data for male';


%% set weights for all real data
weights = setweights(data, []);
weights.tL_f = 5 * weights.tL_f;
weights.tL_m = 5 * weights.tL_m;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Group plots
set1 = {'tL_f','tL_m'}; subtitle1 = {'Data for females, males'};
metaData.grp.sets = {set1};
metaData.grp.subtitle = {subtitle1};

%% Discussion points
D1 = 'Males are assumed to differ from females by {p_Am} only';
D2 = 'mod_1: males have equal state variables at b, compared to females';
metaData.discussion = struct('D1',D1, 'D2',D2);  

%% Facts
F1  = 'length-weight: Ww in g = 0.00977*(TL in cm)^3.16';
metaData.bibkey.F1 = 'fishbase';
metaData.facts = struct('F1',F1);

%% Links
metaData.links.id_CoL = 'YYGV'; % Cat of Life
metaData.links.id_ITIS = '167255'; % ITIS
metaData.links.id_EoL = '46568945'; % Ency of Life
metaData.links.id_Wiki = 'Cottus_gobio'; % Wikipedia
metaData.links.id_ADW = 'Cottus_gobio'; % ADW
metaData.links.id_Taxo = '44972'; % Taxonomicon
metaData.links.id_WoRMS = '127196'; % WoRMS
metaData.links.id_fishbase = 'Cottus-gobio'; % fishbase


%% References
bibkey = 'Pete2009'; type = 'techreport'; bib = [ ...
'author = {J.S. Peters}, ' ... 
'year = {2009}, ' ... 
'title = {Kennisdocument donderpad het geslacht Cottus}, ' ... 
'journal = {Sportvisserij Nederland}, ' ... 
'volume = {9}, ' ... 
'series = {Kennisdocument}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{../../../bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Wiki'; type = 'misc'; bib = [ ...
'howpublished = {\url{http://en.wikipedia.org/wiki/Cottus_gobio}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'fishbase'; type = 'misc'; bib = [ ...
'howpublished = {\url{https://www.fishbase.se/summary/Cottus-gobio.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
