function [data, auxData, metaData, txtData, weights] = mydata_Ampullaceana_balthica
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Mollusca';
metaData.class      = 'Gastropoda';
metaData.order      = 'Pulmonata';
metaData.family     = 'Lymnaeidae';
metaData.species    = 'Ampullaceana_balthica';
metaData.species_en = 'Wandering pond snail';

metaData.ecoCode.climate = {'Cfa','Cfb','Dfa','Dfb','Dfc'};
metaData.ecoCode.ecozone = {'TH'};
metaData.ecoCode.habitat = {'0iFc','0iFr','0iFl','0iFp'};
metaData.ecoCode.embryo  = {'Fc'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biD'};
metaData.ecoCode.gender  = {'Hh'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(15); % K, body temp

metaData.data_0     = {'ab_T','tp','am','Lp','Li'};
metaData.data_1     = {'L-Ww'};

metaData.COMPLETE   = 2; % using criteria of LikaKear2011

metaData.author     = {'Christoph Schuer'};
metaData.date_subm  = [2021 5 19];
metaData.email      = {'schuer@bio.uni-frankfurt.de'};
metaData.address    = {'Goethe University Frankfurt'};

metaData.curator    = {'Bas Kooijman'};
metaData.email_cur  = {'salm.kooijman@gmail.com'};
metaData.date_acc   = [2021 07 30];

%% set zero-variate data
data.ab = 11.3; units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = 'Rupp2011';
  temp.ab = C2K(20); units.temp.ab = 'K'; label.temp.ab = 'temperature';
  comment.ab = 'Ruppert measured day of hatching';
data.ab_15 = 22.8; units.ab_15 = 'd'; label.ab_15 = 'age at birth 15 C'; bibkey.ab_15 = 'Rupp2011';
  temp.ab_15 = C2K(15); units.temp.ab_15 = 'K'; label.temp.ab_15 = 'temperature';
  comment.ab_15 = 'Ruppert measured day of hatching';
data.ab_25 = 8.1; units.ab_25 = 'd'; label.ab_25 = 'age at birth 25 C'; bibkey.ab_25 = 'Rupp2011';
  temp.ab_25 = C2K(25); units.temp.ab_25 = 'K'; label.temp.ab_25 = 'temperature';
  comment.ab_25 = 'Ruppert measured day of hatching';
data.tp = 128; units.tp = 'd'; label.tp = 'time since birth at puberty'; bibkey.tp = 'Hall2012';
  temp.tp = C2K(20); units.temp.tp = 'K'; label.temp.tp = 'temperature';
  comment.tp = 'First laying of eggs in Halgreens control group';
data.am = 365; units.am = 'd'; label.am = 'life span'; bibkey.am = 'Rupp2011';
  temp.am = C2K(20); units.temp.am = 'K'; label.temp.am = 'temperature';
  comment.am = 'literature states a life span of 1 year';

data.Lp = 0.911; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = 'Hall2012';
data.Li = 1.717; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = 'Schu2017';
  comment.Li = 'Largest one I encountered, Rupp2011 measured largest at 1.7 cm';

%% set uni-variate data
% length - wet weight
data.LWw = [ ... 
  0.0265193 0.0295154
  0.0508287 0.0189427
  0.424309 0.0110132
  0.556906 0.0400881
  0.618785 0.0268722
  0.859669 0.110132
  0.930387 0.0955947
  0.933753 0.117976
  0.9491 0.122565
  0.976796 0.129956
  0.998895 0.160352
  1.08466 0.14092
  1.09613 0.16696
  1.09613 0.172247
  1.09613 0.181498
  1.10896 0.156216
  1.12265 0.230396
  1.12928 0.17489
  1.13149 0.194714
  1.13149 0.16696
  1.14475 0.196035
  1.14917 0.214537
  1.1558 0.209251
  1.16243 0.193392
  1.17127 0.223789
  1.18674 0.209251
  1.18895 0.217181
  1.20221 0.215859
  1.21105 0.237004
  1.21105 0.244934
  1.21768 0.251542
  1.22431 0.223789
  1.22652 0.242291
  1.23978 0.307048
  1.24199 0.227753
  1.24862 0.293833
  1.24964 0.33977
  1.2522 0.374186
  1.25746 0.240969
  1.26243 0.388718
  1.26409 0.266079
  1.26409 0.280617
  1.2701 0.329827
  1.27138 0.348948
  1.27138 0.286998
  1.2765 0.290058
  1.27778 0.361949
  1.27778 0.316826
  1.27906 0.345888
  1.27956 0.25815
  1.28545 0.28088
  1.28673 0.354301
  1.28673 0.219695
  1.28801 0.35889
  1.28929 0.28088
  1.29696 0.331357
  1.29824 0.344359
  1.29952 0.358125
  1.30336 0.291587
  1.30719 0.381834
  1.30975 0.319885
  1.30975 0.290822
  1.31614 0.292352
  1.3187 0.387188
  1.31998 0.231167
  1.32382 0.302294
  1.3251 0.304589
  1.32766 0.43843
  1.32818 0.370485
  1.3326 0.355947
  1.33405 0.328298
  1.34172 0.426193
  1.35195 0.394071
  1.35707 0.345124
  1.3673 0.41778
  1.36986 0.392542
  1.36986 0.332122
  1.37625 0.43996
  1.37881 0.404014
  1.38776 0.465963
  1.38785 0.318943
  1.38904 0.417015
  1.39032 0.335181
  1.39927 0.39866
  1.40311 0.323709
  1.41206 0.364244
  1.4159 0.263289
  1.43125 0.503439
  1.43253 0.465963
  1.43764 0.372657
  1.44404 0.453726
  1.44659 0.530207
  1.44787 0.404014
  1.44915 0.509557
  1.45171 0.486613
  1.45171 0.348948
  1.46322 0.490437
  1.46833 0.483554
  1.47984 0.639574
  1.48112 0.443019
  1.4824 0.39866
  1.49008 0.404014
  1.50286 0.533266
  1.50414 0.468257
  1.50798 0.508027
  1.50926 0.47667
  1.51693 0.456785
  1.54891 0.562329
  1.54891 0.410132
  1.55018 0.607452
  1.68831 0.647987
  1.69726 0.592156
  1.69982 0.632691];
units.LWw = {'cm', 'g'}; label.LWw = {'length', 'wet weight'};
bibkey.LWw = {'Rupp2011'};

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Facts
F1  = 'Simultaneous hermaphrodie';
metaData.bibkey.F1 = 'Wiki';
F2  = 'Taxonomy disputed';
metaData.bibkey.F2 = 'Wiki';
metaData.facts = struct('F1',F1, 'F2',F2);

%% Links
metaData.links.id_CoL = 'D7YW'; % Cat of Life
metaData.links.id_ITIS = ''; % ITIS
metaData.links.id_EoL = '52587548'; % Ency of Life
metaData.links.id_Wiki = 'Radix_balthica'; % Wikipedia
metaData.links.id_ADW = ''; % ADW
metaData.links.id_Taxo = '5246343'; % Taxonomicon
metaData.links.id_WoRMS = '1288085'; % WoRMS
metaData.links.id_molluscabase = '1288085'; % molluscabase


%% References
bibkey = 'Hall2012'; type = 'article'; bib = [ ...
'author = {Hall2012 et al.}, ' ... 
'title = {Effects of 17a-ethinylestradiol on individual life-history parameters and estimated population growth rates of the freshwater gastropods Radix balthica and Bithynia tentaculata}, ' ... 
'journal = {Ecotoxicology}, ' ... 
'year = {2012}, ' ... 
'doi = {10.1007/s10646-011-0841-8}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Rupp2011'; type = 'phdthesis'; bib = [ ...
'author = {Katharina Ruppert}, ' ... 
'title = {Vergleichende Sensitivit\"{a}tsanalyse einer invasiven (\emph{Melanoides tuberculata}) und indigenen {S}chnecke (\emph{Radix baltica}) gegen\"{u}ber {P}yrimethanil bei verschiedenen {T}emperaturen}, ' ... 
'school = {Goethe University Frankfurt}, ' ... 
'year = {2011}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Schu2017'; type = 'misc'; bib = [ ...
'author = {Christoph Sch\"{u}r}, ' ... 
'note = {measurements by myself}, ' ... 
'year = {2017}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Wiki'; type = 'misc'; bib = [ ...
'author = {Wikipedia}, ' ... 
'year = {2021-05-19}, ' ... 
'howpublished = {\url{https://en.wikipedia.org/wiki/Radix_balthica}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
