function [data, auxData, metaData, txtData, weights] = mydata_Pogona_barbata
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Reptilia';
metaData.order      = 'Squamata';
metaData.family     = 'Agamidae';
metaData.species    = 'Pogona_barbata';
metaData.species_en = 'Bearded Dragon';

metaData.ecoCode.climate = {'Cfa','Cfb','Csa'};
metaData.ecoCode.ecozone = {'TA'};
metaData.ecoCode.habitat = {'0iTf','0iTi','0iTs'};
metaData.ecoCode.embryo  = {'Tt'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'0iO'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(35); % K, body temp

metaData.data_0     = {'ab'; 'aR'; 'ap'; 'am'; 'Lb'; 'Lp'; 'Li'; 'Wwb'; 'Wwp'; 'Wwi'; 'Wdb'; 'Ri'; 'E0'};
metaData.data_1     = {'t-L'; 't-Ww'; 'L-Ww'; 'L-N'};

metaData.COMPLETE   = 2.7; % using criteria of LikaKear2011

metaData.author     = {'Christopher Gatto'};
metaData.date_subm  = [2020 9 17];
metaData.email      = {'christopher.gatto@monash.edu'};
metaData.address    = {'Monash University'};

metaData.curator    = {'Bas Kooijman'};
metaData.email_cur  = {'salm.kooijman@gmail.com'};
metaData.date_acc   = [2020 9 17];

%% set zero-variate data
data.ab = 77; units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = {'Done2006'};
  temp.ab = C2K(29); units.temp.ab = 'K'; label.temp.ab = 'temperature';
data.tp = 390; units.tp = 'd'; label.tp = 'time since birth at puberty'; bibkey.tp = {'BDTank'};
  temp.tp = C2K(25); units.temp.tp = 'K'; label.temp.tp = 'temperature';
  comment.tp = 'between 8 and 18 months';
data.am = 3650; units.am = 'd'; label.am = 'life span'; bibkey.am = {'DeVo2011'};
  temp.am = C2K(25); units.temp.am = 'K'; label.temp.am = 'temperature';
  comment.am = 'Based on captive animals';

data.Lb = 3.9; units.Lb = 'cm'; label.Lb = 'length at birth'; bibkey.Lb = {'WalkRept'};  
data.Lp = 12; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = {'StauBoot2003'};
data.Li = 25; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = {'StauBoot2003'};

data.Wwb = 2.81; units.Wwb = 'g'; label.Wwb = 'wet weight at birth'; bibkey.Wwb = {'WhitHoll2017'};
data.Wwp = 56.7; units.Wwp = 'g'; label.Wwp = 'wet weight at puberty'; bibkey.Wwp = {'StauBoot2003'};
  comment.Wwp = 'Calculated using lengths from StauBoot2003 and relationship between mass and SVL in Gatt2013';
data.Wwi = 718; units.Wwi = 'g'; label.Wwi = 'ultimate wet weight'; bibkey.Wwi = {'Gatt2013'};
  comment.Wwi = 'Calculated from museum specimens';

data.Ri = 0.247; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = {'AmeyWhit2000'};
  temp.Ri = C2K(25); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = 'Calculated by multiplying 30 eggs/clutch by 3 clutches per year';
data.tR = 730; units.tR = 'd'; label.tR = 'time since birth at first egg production'; bibkey.tR = {'BDTank'};
  temp.tR = C2K(25); units.temp.tR = 'K'; label.temp.tR = 'temperature';

data.E0 = 23193.5; units.E0 = 'J'; label.E0 = 'initial energy content'; bibkey.E0 = {'Vitt1978'};
  comment.E0 = 'Calculated using energy content equation in Vitt1978, based on 3g egg from museum data in Gatt2013';

%% set uni-variate data
% length - wet weight
data.LWw = [ ... 
  8.5 31.2
  10 40.3
  12 56.7
  14 79.7
  16 112.2
  18 157.8
  20 222.1
  22 312.4
  24 439.6
  26 618.4];
units.LWw = {'cm', 'g'}; label.LWw = {'length', 'wet weight'};
bibkey.LWw = 'Gatt2013';
comment.LWw = 'Data from museum specimens';

% time - length
data.tL = [ ... 
  51 4.45
  65 5.72
  83 6.35
  111 8.26
  125 8.89
  142 10.16
  159 10.8
  181 11.43
  260 12.07
  326 12.7
  394 14.29
  766 18.42
  1095 19.43
  1460 20.82
  1825 21.9
  2190 22.8
  2555 23.5
  2920 24.2
  3285 24.7
  3650 25];
data.tL(13:end,:) = []; % remove added points
units.tL = {'d', 'cm'}; label.tL = {'time', 'SVL'};
temp.tL = C2K(25); units.temp.tL = 'K'; label.temp.tL = 'temperature';
bibkey.tL = 'BearDrag';
%comment.tL = 'Age up to 766 from BearDrag, added SVL of 25cm at 3650 days of age and then estimated length at ages 1095-3285.';

data.tWw = [ ...
1.014	11.966
7.548	19.402
15.084	23.840
20.606	20.812
28.147	32.728
35.686	40.158
41.721	52.084
48.253	58.024
55.292	68.448
62.836	84.852
69.377	101.262
77.424	117.663
84.466	134.070
91.508	148.981
98.548	162.396
106.607	195.250
111.132	202.699
120.180	214.605
127.728	235.496
135.266	242.926
143.312	257.830
147.833	259.296
156.370	259.241
162.914	281.634
165.435	295.079
171.466	301.022
174.482	305.490
182.011	299.457
191.074	332.304
198.611	338.238
203.138	348.678
212.686	357.590
218.218	368.024
226.255	370.963
233.285	369.421
240.824	378.346
246.351	382.797
251.885	396.223
262.444	414.103
267.970	417.058
275.518	437.949
281.044	439.408
287.586	458.810
295.111	448.291
322.727	440.631
329.773	463.021
336.294	452.509
343.321	446.480
351.881	477.834
358.911	477.788
365.943	479.238
367.963	494.182
369.982	509.126
383.049	522.502
394.095	519.438
402.139	531.351
407.671	543.281
413.698	543.242
421.240	556.654
428.788	577.545
435.821	580.490
443.356	583.432
449.384	586.384
456.905	569.882
462.932	569.843
471.987	592.220
477.007	589.195];
units.tWw = {'d', 'g'}; label.tWw = {'time', 'wet weight'};
temp.tWw = C2K(25); units.temp.tWw = 'K'; label.temp.tWw = 'temperature';
bibkey.tWw = 'BDOrg';
comment.tWw = 'pet dragon Peppa';

% length - yearly fecundity
data.LN = [ ... 
  13.1 49.3
  14 51.5
  15 54
  16 56.4
  17 58.8
  18 61.3
  19 63.7
  20 66.1
  21 68.6
  22.8 72.9];
units.LN = {'cm', '#'}; label.LN = {'length', 'yearly fecundity'};
temp.LN = C2K(25); units.temp.LN = 'K'; label.temp.LN = 'temperature';
bibkey.LN = 'Gatt2013';
comment.LN = 'Based on number of eggs in museum specimens';

%% set weights for all real data
weights = setweights(data, []);
weights.Wwi = 5 * weights.Wwi;
weights.Wwp = 0 * weights.Wwp; % not consistent with LWw data
weights.tp = 0 * weights.tp; % very large uncertainty
weights.tWw = 10 * weights.tWw;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);
weights.psd.v = 2 * weights.psd.v;

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Discussion points
D1 = 'Temperature of 25C based on modelling using NicheMapR of bearded dragon body temperatures in the wild';
D2 = 'tp was ignorged because of large uncertainty, Wwp because of inconsistency with LWw data';
metaData.discussion = struct('D1',D1, 'D2',D2);

%% Links
metaData.links.id_CoL = '4KV6P'; % Cat of Life
metaData.links.id_ITIS = '1056848'; % ITIS
metaData.links.id_EoL = '790994'; % Ency of Life
metaData.links.id_Wiki = 'Pogona_barbata'; % Wikipedia
metaData.links.id_ADW = 'Pogona_barbata'; % ADW
metaData.links.id_Taxo = '90686'; % Taxonomicon
metaData.links.id_WoRMS = ''; % WoRMS
metaData.links.id_ReptileDB = 'genus=Pogona&species=barbata'; % ReptileDB
metaData.links.id_AnAge = 'Pogona_barbata'; % AnAge


%% References
bibkey = 'Vitt1978'; type = 'Article'; bib = [ ... 
'title = {Caloric content of lizard and snake (Reptilia) eggs and bodies and the conversion of weight to caloric data}, '...
'volume = {12(1)}, '...
'journal = {Journal of Herpetology}, '...
'author = {Vitt, Laurie J}, '...
'year = {1978}, '...
'pages = {65-72}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'StauBoot2003'; type = 'Article'; bib = [ ... 
'title = {Allometry in the bearded dragon \emph{Pogona barbata} ({S}auria: {A}gamidae): sex and geographic differences}, '...
'volume = {32}, '...
'journal = {Australian Zoologist}, '...
'author = {Stauber, Andrew and Booth, David}, '...
'year = {2003}, '...
'pages = {238-245}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'AmeyWhit2000'; type = 'Article'; bib = [ ... 
'title = {Seasonal patterns of plasma steroid hormones in males and females of the bearded dragon lizard, \emph{Pogona barbata}},'...
'volume = {117}, '...
'journal = {General and Comparative Endocrinology}, '...
'author = {Amey, Andrew P and Whittier, Joan M}, '...
'year = {2000}, '...
'pages = {335-342}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'WhitHoll2017'; type = 'Article'; bib = [ ... 
'title = {Sex determination mode does not affect body or genital development of the central bearded dragon (\emph{Pogona vitticeps})}, '...
'volume = {8}, '...
'journal = {EvoDevo}, '...
'author = {Whiteley, Sarah L. and Holleley, Clare E. and Ruscoe, Wendy A and Castelli, Meghan and Whitehead, Darryl L. and Lei, Juan and Georges, Arthur and Weisbecker, Vera},'...
'year = {2017}, '...
'pages = {25}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Done2006'; type = 'Book'; bib = [ ...  
'author = {Doneley, Bob}, ' ...
'year = {2006}, ' ...
'title  = {Caring for the bearded dragon}, ' ...
'publisher = {North American Veterinary Conference}, ' ...
'pages = {}, ' ...
'howpublished = {\url{url https://www.cabi.org/ISC/FullTextPDF/2006/20063121821.pdf}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'DeVo2011'; type = 'Book'; bib = [ ...  
'author = {De Vosjoli, Philippe}, ' ...
'year = {2011}, ' ...
'title  = {The Bearded Dragon Manual}, ' ...
'publisher = {Fox Chapel Publishing}, ' ...
'pages = {}, ' ...
'howpublished = {}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BDOrg'; type = 'Misc'; bib = [ ...
'author = {Bearded Dragon.Org}, ' ...
'note  = {Website detailing growth rates of captive bearded dragons}, ' ...
'year = {2018}, ' ...
'howpublished = {\url{https://www.beardeddragon.org/forums/viewtopic.php?p=1870850}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BearDrag'; type = 'Misc'; bib = [ ...
'author = {Bearded Dragon Pages}, ' ...
'note  = {Website detailing growth rates of captive bearded dragons}, ' ...
'year = {2000}, ' ...
'howpublished = {\url{http://users.erols.com/ziring/dragon-pics.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'WalkRept'; type = 'Misc'; bib = [ ...
'author = {Walkabout Reptiles}, ' ...
'note  = {Website on the care and husbandry of bearded dragons}, ' ...
'year = {2007}, ' ...
'howpublished = {\url{http://www.walkaboutreptiles.com.au/csfsindex.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'BDTank'; type = 'Misc'; bib = [ ...
'author = {Bearded Dragon Tank}, ' ...
'note  = {Website on the care and husbandry of bearded dragons}, ' ...
'year = {}, ' ...
'howpublished = {\url{https://beardeddragontank.com/when-do-bearded-dragons-hit-puberty}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Gatt2013'; type = 'mastersthesis'; bib = [ ... 
'title = {Modelling a lizards life history and population responses to current and novel environments}, '...
'author = {Gatto, Christopher}, '...
'year = {2013}, '...
'school = {University of Melbourne}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

