function [data, auxData, metaData, txtData, weights] = mydata_Cygnus_olor
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata'; 
metaData.class      = 'Aves'; 
metaData.order      = 'Anseriformes'; 
metaData.family     = 'Anatidae';
metaData.species    = 'Cygnus_olor'; 
metaData.species_en = 'Mute swan'; 

metaData.ecoCode.climate = {'BWk', 'Cfb', 'Dfa', 'Dfb'};
metaData.ecoCode.ecozone = {'TH'};
metaData.ecoCode.habitat = {'biF'};
metaData.ecoCode.embryo  = {'Tnsf'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biCi', 'xiH'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(41.3); % K
metaData.data_0     = {'ab'; 'ap'; 'aR'; 'am'; 'Wwb'; 'Wwi'; 'Ri'}; 
metaData.data_1     = {'t-Ww'}; 

metaData.COMPLETE = 2.5; % using criteria of LikaKear2011

metaData.author      = {'Bas Kooijman'};    
metaData.date_subm   = [2020 11 28];              
metaData.email       = {'bas.kooijman@vu.nl'};            
metaData.address     = {'VU University Amsterdam'};   

metaData.author_mod_2   = {'Bas Kooijman'};    
metaData.date_mod_2     = [2022 11 27];              
metaData.email_mod_2    = {'bas.kooijman@vu.nl'};            
metaData.address_mod_2  = {'VU University Amsterdam'};   

metaData.author_mod_3   = {'Bas Kooijman','Starrlight Augustine'};    
metaData.date_mod_3     = [2023 06 24];              
metaData.email_mod_3    = {'bas.kooijman@vu.nl'};            
metaData.address_mod_3  = {'VU University, Amsterdam'};   

metaData.curator     = {'Starrlight Augustine'};
metaData.email_cur   = {'starrlight@tecnico.ulisboa.pt'}; 
metaData.date_acc    = [2023 06 24];

%% set data
% zero-variate data

data.ab = 36;   units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = {'Wiki','Bech1980'};   
  temp.ab = C2K(36); units.temp.ab = 'K'; label.temp.ab = 'temperature';
data.tx = 135; units.tx = 'd'; label.tx = 'time since birth at fledging'; bibkey.tx = {'Wiki','Bech1980'};   
  temp.tx = C2K(41.3); units.temp.tx = 'K'; label.temp.tx = 'temperature';
  comment.tx = '120 till 150 d';
data.tp = 135*3; units.tp = 'd'; label.tp = 'time since birth at fledging'; bibkey.tp = 'guess';   
  temp.tp = C2K(41.3); units.temp.tp = 'K'; label.temp.tp = 'temperature';
data.tR = 1095; units.tR = 'd'; label.tR = 'time since birth at 1st brood'; bibkey.tR = {'AnAge','Bech1980'};
  temp.tR = C2K(41.3); units.temp.tR = 'K'; label.temp.tR = 'temperature';
data.am = 14600; units.am = 'd'; label.am = 'life span'; bibkey.am = {'AnAge','Bech1980'};   
  temp.am = C2K(41.3); units.temp.am = 'K'; label.temp.am = 'temperature'; 

data.Wwb = 157; units.Wwb = 'g'; label.Wwb = 'wet weight at birth'; bibkey.Wwb = 'LeeuBeek1991';
data.Wwi = 10.6e3; units.Wwi = 'g'; label.Wwi = 'ultimate wet weight for females'; bibkey.Wwi = 'Wiki';
  comment.Wwi = '7.6 till 10.6 kg';
data.Wwim = 14.3e3; units.Wwim = 'g'; label.Wwim = 'ultimate wet weight for males'; bibkey.Wwim = 'Wiki';
  comment.Wwim = '9.2 till 14.3 kg';

data.Ri  = 6/365; units.Ri  = '#/d'; label.Ri  = 'maximum reprod rate'; bibkey.Ri  = {'Wiki','Bech1980'};   
 temp.Ri = C2K(41.3); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
 comment.Ri = '4 till 10 eggs per clutch; 1 clutch per yr';

% uni-variate data
% time - wet weight
data.tWw = [ ... % time since birth (d), weight (g)
0.0	    157.1
2.3	    196.4
11.7	392.8
15.5	353.5
18.3	805.2
26.6	1492.6
27.2	1099.8
30.1	1021.3
31.6	2828.2
33.1	2631.8
37.2	1630.1
38.8	3162.0
40.9	2671.0
41.1	2612.1
43.8	2317.5
44.8	3260.2
45.8	4517.2
49.4	3731.6
52.0	3437.0
53.5	5734.9
53.6	4144.0
53.9	4792.1
56.0	3869.1
57.6	5381.3
59.6	5224.2
59.7	6775.8
59.9	5243.9
64.5	4752.9
66.8	5086.7
67.7	7188.2
68.1	6049.1
72.0	7934.5
72.2	5538.5
74.3	7856.0
77.7	7698.9
77.9	6422.3
79.7	8170.2
81.3	6716.9
81.9	9211.1
83.2	8072.0
85.0	7306.1
86.2	6893.6
88.8	9289.7
89.2	8366.6
91.3	7620.3
93.3	7345.3
93.8	7895.3
95.7	8936.2
96.0	9643.2
100.1	8111.3
100.4	8307.7
102.5	10212.8
103.2	9152.2
103.3	8425.5
107.3	8504.1
109.7	10311.0
110.0	10212.8
110.9	9545.0
112.4	8779.1
112.9	10094.9
113.8	9132.6
115.8	9584.3
117.8	9839.6
118.0	10114.6
118.1	9230.8
119.0	8798.7
123.8	9702.1
124.3	10369.9
125.4	8661.2
125.9	9466.4
126.2	9230.8
126.4	10291.3
129.1	8680.9
131.1	8445.2]; 
units.tWw   = {'d', 'g'};  label.tWw = {'time since birth', 'wet weight'};  
temp.tWw    = C2K(41.3);  units.temp.tWw = 'K'; label.temp.tWw = 'temperature';
bibkey.tWw = {'Bech1980','LeeuBeek1991'};
  
%% set weights for all real data
weights = setweights(data, []);
weights.tWw = weights.tWw * 2;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);
weights.psd.k_J = 0; weights.psd.k = 1;

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Discussion points
D1 = 'males are assumed to differ from females by {p_Am} only';
D2 = 'functional response is assumed to reduce somewhat near fledging';
D3 = 'mod_1: v is reduced';
D4 = 'mod_2: Puberty is assumed to coincide with fledging with a waiting time to first brood';
D5 = 'mod_3: Pseudo-data point k is used, rather than k_J; Parameter t_R is added, replacing clutch interval t_N. Postnatal T is based on PrinPres1991, see <a href="https://debtool.debtheory.org/lib/pet/html/get_T_Aves.html">get_T_Aves</a>. See further the <a href="https://debportal.debtheory.org/docs/Revision.html">revision page, theme puberty</a>';

metaData.discussion = struct('D1',D1, 'D2',D2, 'D3',D3, 'D4',D4, 'D5',D5);  

%% Links
metaData.links.id_CoL = '32ZQB'; % Cat of Life
metaData.links.id_ITIS = '174985'; % ITIS
metaData.links.id_EoL = '45510543'; % Ency of Life
metaData.links.id_Wiki = 'Cygnus_olor'; % Wikipedia
metaData.links.id_ADW = 'Cygnus_olor'; % ADW
metaData.links.id_Taxo = '52049'; % Taxonomicon
metaData.links.id_WoRMS = '159090'; % WoRMS
metaData.links.id_avibase = '694C127A5D849FFE'; % avibase
metaData.links.id_birdlife = 'mute-swan-cygnus-olor'; % birdlife
metaData.links.id_AnAge = 'Cygnus_olor'; % AnAge

%% References
bibkey = 'Wiki'; type = 'Misc'; bib = ...
'howpublished = {\url{http://en.wikipedia.org/wiki/Cygnus_olor}}';
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{../../../bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'LeeuBeek1991'; type = 'Article'; bib = [ ... 
'author = {Joep J de Leeuw and Jan H Beekman}, ' ... 
'year = {1991}, ' ...
'title = {Growth and biometry of Mute Swan Cygnus olor cygnets in {G}roningen, the {N}etherlands}, ' ...
'journal = {Wildfowl}, ' ...
'volume = {Supplement 1}, ' ...
'pages = {288-295}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Bech1980'; type = 'Article'; bib = [ ... 
'author = {Claus Bech}, ' ... 
'year = {1980}, ' ...
'title = {Body temperature, metabolic rate, and insulation in winter and summer acclimatized mute swans (\emph{Cygnus olor})}, ' ...
'journal = {J. Comp. Physiol.}, ' ...
'volume = {136}, ' ...
'pages = {61-66}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'AnAge'; type = 'Misc'; bib = ...
'howpublished = {\url{http://genomics.senescence.info/species/entry.php?species=Cygnus_olor}}';
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'ADW'; type = 'Misc'; bib = ...
'howpublished = {\url{https://animaldiversity.org/accounts/Cygnus_olor/}}';
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];