function [prdData, info] = predict_Cygnus_olor(par, data, auxData)
% file generated by prt_predict

% unpack par, data, auxData
cPar = parscomp_st(par); vars_pull(par);
vars_pull(cPar);  vars_pull(data);  vars_pull(auxData);

 

% compute temperature correction factors
pars_T = T_A;
TC_ab = tempcorr(temp.ab, T_ref, pars_T);
TC    = tempcorr(temp.am, T_ref, pars_T); kT_M = TC * k_M;

% life cycle
pars_tx = [g; k; l_T; v_Hb; v_Hx];  % compose parameter vector
[tau_x, tau_b, l_x, ~] = get_tp(pars_tx, f); % -, scaled times & lengths at f
pars_tp = [g; k; l_T; v_Hb; v_Hp];  % compose parameter vector
[tau_p, tau_b, l_p, l_b, info] = get_tp(pars_tp, f); % -, scaled times & lengths at f
if info == 0; prdData = []; return; end

% birth
L_b = L_m * l_b;                  % cm, structural length at birth
a_b = tau_b/ k_M/ TC_ab;    % d, age at birth
Ww_b = L_b^3 * (1 + f * ome);     % g, wet weight at birth

% fledging/puberty
t_x = (tau_x - tau_b)/ kT_M;      % d, time since birth at fledging
t_p = (tau_p - tau_b)/ kT_M;      % d, time since birth at fledging

% ultimate
l_i = f - l_T; % -, scaled ultimate length
L_i = L_m * l_i; % cm, ultimate structural length
Ww_i = L_i^3 * (1 + f * ome); % g, ultimate wet weight 
pars_tm = [g; l_T; h_a/ k_M^2; s_G]; % compose parameter vector
tau_m = get_tm_s(pars_tm, f, l_b); % -, scaled mean life span
a_m = tau_m/ kT_M; % d, mean life span

% reproduction
pars_R = [kap; kap_R; g; k_J; k_M; L_T; v; U_Hb; U_Hp]; % compose parameter vector
R_i = TC * reprod_rate(L_i, f, pars_R); % #/d, ultimate reproduction rate

% males
p_Am_m = z_m * p_M/ kap; % J/d.cm^2, {p_Am} spec assimilation flux
E_m_m = p_Am_m/ v; % J/cm^3, reserve capacity [E_m]
g_m = E_G/ (kap* E_m_m); % -, energy investment ratio
m_Em_m = y_E_V * E_m_m/ E_G; % mol/mol, reserve capacity
ome_m = m_Em_m * w_E/ w_V; % -, contribution of reserve to weight
L_mm = v/ k_M/ g_m; L_im = f * L_mm; % cm, max ultimate length
Ww_im = L_im^3 * (1 + f * ome_m); % g, ultimate wet weight

% pack to output
prdData.ab = a_b;
prdData.tx = t_x;
prdData.tp = t_p;
prdData.tR = t_R;
prdData.am = a_m;
prdData.Wwb = Ww_b;
prdData.Wwi = Ww_i;
prdData.Wwim = Ww_im;
prdData.Ri = R_i;

  % uni-variate data
  
  tf = [60 90 135; f_060 f_090 f_135]'; tf(:,1) = tf(:,1) * kT_M;
  tvel = get_tp(pars_tp, tf, [], tWw(:,1)*kT_M);
  EWw = (L_m * tvel(:,4)).^3 .* (1 + tvel(:,3) * ome);   % g, weight
  
  % pack to output
  prdData.tWw = EWw;

end
    