function [data, auxData, metaData, txtData, weights] = mydata_Muraenolepis_marmorata
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Gadiformes';
metaData.family     = 'Muraenolepididae';
metaData.species    = 'Muraenolepis_marmorata';
metaData.species_en = 'Marbled moray cod';

metaData.ecoCode.climate = {'ME'};
metaData.ecoCode.ecozone = {'MAS'};
metaData.ecoCode.habitat = {'jiMd','0jMcp'};
metaData.ecoCode.embryo  = {'Mp'}; 
metaData.ecoCode.migrate = {'Mo'};
metaData.ecoCode.food    = {'biHa','biCiw','biCim','biCid','biCik','biCvf'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(5); % K, body temp

metaData.data_0     = {'am';'Lp';'Li';'Wwb';'Wwp';'Wwi';'Ri'};
metaData.data_1     = {'t-L'};

metaData.COMPLETE   = 2.5; % using criteria of LikaKear2011

metaData.author   = {'Bas Kooijman'};        
metaData.date_subm = [2023 11 23];                           
metaData.email    = {'bas.kooijman@vu.nl'};                 
metaData.address  = {'VU University, Amsterdam'}; 

metaData.curator     = {'Dina Lika'};
metaData.email_cur   = {'lika@uoc.gr'}; 
metaData.date_acc    = [2023 11 23];

%% set zero-variate data
data.am = 14*365; units.am = 'd'; label.am = 'life span'; bibkey.am = 'KompRoja1996';
  temp.am = C2K(5); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lp = 20; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = 'KompRoja1996';
data.Li = 44; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = 'fishbase';

data.Wwb = 1.4e-4; units.Wwb = 'g';   label.Wwb = 'wet weight at birth'; bibkey.Wwb = 'guess';
  comment.Wwb = 'based on egg diameter of 0.65 mm: pi/6*0.065^3'; 
data.Wwp = 65; units.Wwp = 'g';   label.Wwp = 'wet weight at puberty';   bibkey.Wwp = {'fishbase','KompRoja1996'};
  comment.Wwp = 'based on 0.00437*Lp^3.11, see F1';
data.Wwi = 780; units.Wwi = 'g';   label.Wwi = 'ultimate wet weight';    bibkey.Wwi = 'fishbase';
  comment.Wwi = 'based on 0.00437*Li^3.11, see F1, gives 564 g';

data.Ri = 3e4/365; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = 'guess';
  temp.Ri = C2K(5); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = 'guessed yearly fecundity 30000 eggs per year';

%% set uni-variate data

% time - length
data.tL = [ ... % time since birth (yr), total length (cm)
    5 18.6
    5 19.0
    5 19.4
    5 19.7
    5 19.8
    5 20.0
    6 20.3
    5 20.4
    5 20.5
    5 20.5
    6 20.8
    5 21.0
    5 21.0
    5 21.2
    6 21.2
    5 21.3
    5 21.4
    5 21.5
    5 22.5
    5 22.5
    6 22.5
    6 22.6
    6 22.8
    6 22.8
    6 23.1
    6 23.5
    5 23.6
    8 23.7
    6 24.1
    6 24.6
    6 24.7
    6 25.3
    6 26.1
    7 26.1
    5 26.3
    6 26.9
   10 27.0
    7 27.0
    6 27.2
    7 27.5
    6 27.7
    7 27.8
    7 28.2
    8 28.2
    7 28.2
    7 29.0
    8 29.0
   10 29.3
    7 29.5
    9 29.8
    7 30.8
    8 34.9
    9 35.0
   13 37.1
    9 37.6];
data.tL(:,1) = 365*(data.tL(:,1)); % convert tr to d
[~, i] = sort(data.tL(:,1)); data.tL = data.tL(i,:);
for i=2:size(data.tL,1);if data.tL(i,1)<=data.tL(i-1,1);data.tL(i,1)=data.tL(i-1,1)+1e-3;end;end
units.tL = {'d', 'cm'}; label.tL = {'time', 'length'};
temp.tL = C2K(5); units.temp.tL = 'K'; label.temp.tf = 'temperature';
bibkey.tL = {'KompRoja1996'};

%% set weights for all real data
weights = setweights(data, []);
weights.tL = 3 * weights.tL;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Discussion points
D1  = 'males are assumed not to differ from females';
metaData.discussion = struct('D1',D1);

%% Facts
F1 = 'weight-length relationship: Ww in g = 0.00437*(TL in cm)^3.11';
metaData.bibkey.F1 = 'fishbase'; 
F2 = 'known only from the Crozet, Kerguelen and Heards islands.';
metaData.bibkey.F2 = 'fishbase'; 
metaData.facts = struct('F1',F1, 'F2',F2);

%% Links
metaData.links.id_CoL = '6S2YH'; % Cat of Life
metaData.links.id_ITIS = ''; % ITIS
metaData.links.id_EoL = '46565113'; % Ency of Life
metaData.links.id_Wiki = 'Muraenolepis_marmorata'; % Wikipedia
metaData.links.id_ADW = 'Muraenolepis_marmorata'; % Anim Div. Web
metaData.links.id_Taxo = '3417627'; % Taxonomicon
metaData.links.id_WoRMS = '313346';
metaData.links.id_fishbase = 'Muraenolepis-marmorata';

%% References
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'KompRoja1996'; type = 'article'; bib = [ ...
'doi = {10.3750/AIP1996.26.2.03}, ' ...
'author = {Andrzej Kompowski and Carlos Rojas}, ' ... 
'title = {VERTICAL DISTRIBUTION, AGE AND GROWTH RATE OF \emph{Muraenolepis marmorata} {G}UNTHER, 1880 ({G}ADIFORMES, {M}URAENOLEPIDAE) IN THE AREA OF {S}OUTH {G}EORGIA ({A}NTARCTICA)}, ' ... 
'journal = {Acta Ichthyologica et Piscatoria}, ' ... 
'year = {1996}, ' ... 
'volume = {26(2)}, ' ...
'pages = {49-62}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'fishbase'; type = 'Misc'; bib = [...
'howpublished = {\url{http://www.fishbase.se/summary/Muraenolepis-marmorata.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

