function [data, auxData, metaData, txtData, weights] = mydata_Portunus_trituberculatus
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Arthropoda';
metaData.class      = 'Malacostraca';
metaData.order      = 'Decapoda';
metaData.family     = 'Portunidae';
metaData.species    = 'Portunus_trituberculatus';
metaData.species_en = 'Gazami crab';

metaData.ecoCode.climate = {'Aw','Cfa','Dfa','Dwa'};
metaData.ecoCode.ecozone = {'MPNW','MPy','MPc','MS'};
metaData.ecoCode.habitat = {'jiMi','0bMcb','bjMp'};
metaData.ecoCode.embryo  = {'Mbf'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biD','bjP','jiCi','jiS'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(25); % K, body temp

metaData.data_0     = {'ab';'am';'Lj';'Lp';'Li';'Wwj';'Ri'};
metaData.data_1     = {'L-Ww';'t-L';'t-Ww'};

metaData.COMPLETE   = 2.5; % using criteria of LikaKear2011

metaData.author     = {'Dong Shipeng'};
metaData.date_subm  = [2022 2 11];
metaData.email      = {'dongshipeng@stu.ouc.edu.cn'};
metaData.address    = {'Ocean University of China'};

metaData.curator    = {'Bas Kooijman'};
metaData.email_cur  = {'salm.kooijman@gmail.com'};
metaData.date_acc   = [2022 2 17];

%% set zero-variate data
data.ab = 7; units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = 'Dong2012';
  temp.ab = C2K(15); units.temp.ab = 'K'; label.temp.ab = 'temperature';
data.am = 730; units.am = 'd'; label.am = 'life span'; bibkey.am = 'Dong2012';
  temp.am = C2K(20); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lj = 0.383; units.Lj = 'cm'; label.Lj = 'length at end acceleration'; bibkey.Lj = 'GaoWang2016';
data.Li = 25; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = {'Wiki'};

data.Ri = 7296; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = 'Dong2012';
  temp.Ri = C2K(13); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';

%% set uni-variate data
% length - wet weight
data.LWw = [ ... 
  1.96087 6.57303
  2.1989 7.52402
  2.3047 8.71563
  2.45582 8.55428
  2.5616 8.5527
  2.69386 10.6189
  2.64285 9.82422
  2.87334 12.9231
  3.25493 13.6333
  3.59876 16.7304
  3.84245 17.2041
  4.03328 20.7012
  4.16927 19.1083
  4.32609 21.5718
  4.57547 24.7499
  4.41489 23.0819
  4.73605 25.7816
  4.86831 28.5638
  4.93634 30.6309
  4.97784 25.2212
  5.84316 39.4469
  7.08443 55.8943
  7.41892 68.2189
  7.84395 68.2126
  7.87429 79.0303
  7.83659 86.1899
  7.98012 83.6423
  8.10667 82.2086
  8.35988 89.6026
  8.30683 74.4897
  8.54676 77.4293
  8.42418 96.2039
  8.56025 101.929
  8.75489 108.767
  8.72648 101.211
  8.90773 92.8558
  8.91711 86.9693
  8.95318 102.878
  9.0609 107.251
  9.1252 114.648
  8.98929 123.082
  9.20848 129.044
  9.46129 99.6089
  9.32354 113.929
  9.49551 120.211
  9.49572 139.142
  9.7013 109.867
  9.77504 115.434
  9.87511 111.375
  9.78273 128.002
  9.88856 132.614
  9.94534 142.397
  10.1588 141.201
  10.089 151.225
  10.378 147.243
  10.2194 159.654
  10.3155 138.176
  10.5402 127.831
  10.6915 139.204
  10.6916 149.068
  10.7522 163.783
  10.943 169.03
  11.1244 169.664
  11.3567 163.137
  11.2318 147.628
  10.9696 183.825
  11.0774 189.233
  11.2171 186.526
  11.2703 211.423
  11.8616 219.289
  12.6114 203.607
  11.7959 255.085
  12.8691 278.138
  13.1317 275.906
  13.3719 306.926];
units.LWw = {'cm', 'g'}; label.LWw = {'length', 'wet weight'};
bibkey.LWw = {'CheLiu2019'};
comment.LWw = 'Data for males';

% time - length
data.tL = [ ... 
  16 1.367
  23 1.941
  32 2.791
  41 4.079
  56 5.63
  76 7.291
  106 8.96
  137 10.665
  171 12.067];
units.tL = {'d', 'cm'}; label.tL = {'time', 'length'};
temp.tL = C2K(23); units.temp.tL = 'K'; label.temp.tL = 'temperature';
bibkey.tL = {'GaoWang2016'};

% time - wet weight
data.tWw = [ ... 
  16 0.32
  23 0.94
  32 2.77
  41 8.3
  56 21.93
  76 45.36
  106 84.24
  137 138.08
  171 205.23];
units.tWw = {'d', 'g'}; label.tWw = {'time', 'wet weight'};
temp.tWw = C2K(23); units.temp.tWw = 'K'; label.temp.tWw = 'temperature';
bibkey.tWw = {'GaoWang2016'};

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;


%% Links
metaData.links.id_CoL = '4M2PW'; % Cat of Life
metaData.links.id_ITIS = '660568'; % ITIS
metaData.links.id_EoL = '2982700'; % Ency of Life
metaData.links.id_Wiki = 'Portunus_trituberculatus'; % Wikipedia
metaData.links.id_ADW = 'Portunus_trituberculatus'; % Anim Div. Web
metaData.links.id_Taxo = '34030'; % Taxonomicon
metaData.links.id_WoRMS = '1061762'; % WoRMS

%% References
bibkey = 'CheLiu2019'; type = 'article'; bib = [ ...
'author = {Che, J. and Liu, M. and Hou, W. and Dong, Z. and Yang, S. and Cheng, Y.  and Wu, X.}, ' ... 
'title = {Growth and Gonadal Development of Pond-reared Male Swimming Crab,  \emph{Portunus trituberculatus}}, ' ... 
'journal = {Chinese Journal of Zoology}, ' ... 
'year = {2019}, ' ... 
'volume = {54}, ' ... 
'pages = {347--361}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Dong2012'; type = 'phdthesis'; bib = [ ...
'author = {Dong, Z.}, ' ... 
'title = {The Study on Morphology, Biochemistry, Molecular Phylogeography and Genetic Diversity of the Swimming Crab \emph{Portunus trituberculatus} along China Coast}, ' ... 
'school = {Shanghai Ocean University}, ' ... 
'year = {2012}, ' ... 
'address = {21p}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'GaoWang2016'; type = 'article'; bib = [ ...
'author = {Gao, T. and Wang, Y. and Bao, X. and Ren, Z. and Mu, C. and Wang, C.}, ' ... 
'title = {Study on the characteristics of molting and growth of \emph{Portunus trituberculatus} cultured in single individual basket}, ' ... 
'journal = {Journal of Biology}, ' ... 
'year = {2016}, ' ... 
'volume = {33}, ' ... 
'pages = {41--46}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Wiki'; type = 'misc'; bib = [ ...
'howpublished = {\url{https://en.wikipedia.org/wiki/Portunus_trituberculatus}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
