function [prdData, info] = predict_Portunus_trituberculatus(par, data, auxData)
% file generated by prt_predict

% unpack par, data, auxData
cPar = parscomp_st(par); vars_pull(par);
v2struct(par); v2struct(cPar); v2struct(data); v2struct(auxData);

% compute temperature correction factors
pars_T = T_A;
TC_ab = tempcorr(temp.ab, T_ref, pars_T);
TC_am = tempcorr(temp.am, T_ref, pars_T);
TC_Ri = tempcorr(temp.Ri, T_ref, pars_T);
TC_tL = tempcorr(temp.tL, T_ref, pars_T);
TC_tWw = tempcorr(temp.tWw, T_ref, pars_T);

% life cycle
pars_tj = [g; k; l_T; v_Hb; v_Hj; v_Hp];
[tau_j, tau_p, tau_b, l_j, l_p, l_b, l_i, rho_j, rho_B, info] = get_tj(pars_tj, f);

if info == 0
  prdData = []; return;
end

% birth
a_b = t_0 + tau_b/ k_M/ TC_ab;    % d, age at birth

% end of acceleration
L_j = L_m * l_j; % cm, structural length at end of acceleration
Lw_j = L_j/ del_M; % cm, physical length at end acceleration

% ultimate
L_i = L_m * l_i; % cm, ultimate structural length
Lw_i = l_i * L_m/ del_M; % cm, ultimate physical length
pars_tm = [g; l_T; h_a/ k_M^2; s_G]; % compose parameter vector
tau_m = get_tm_s(pars_tm, f, l_b); % -, scaled mean life span
a_m = tau_m/ k_M/ TC_am; % d, mean life span

% reproduction
pars_R = [kap; kap_R; g; k_J; k_M; L_T; v; U_Hb; U_Hj; U_Hp]; % compose parameter vector
R_i = TC_Ri * reprod_rate_j(L_i, f, pars_R); % #/d, ultimate reproduction rate

% pack to output
prdData.ab = a_b;
prdData.am = a_m;
prdData.Lj = Lw_j;
prdData.Li = Lw_i;
prdData.Ri = R_i;

% length - wet weight
LWw = (LWw(:,1) * del_M).^3 * (1 + f_LWw_f * ome); % g, wet weight

% time - length
[tau_j, tau_p, tau_b, l_j, l_p, l_b, l_i, rho_j, rho_B] = get_tj(pars_tj, f_tL);
r_B = TC_tL * rho_B * k_M; r_j = TC_tL * rho_j * k_M; t_j = (tau_j - tau_b)/ k_M/ TC_tL;
L_b = L_m * l_b;  L_j = L_m * l_j; L_i = L_m * l_i;
L_bj = L_b * exp(tL(tL(:,1) < t_j,1) * r_j/ 3);
L_ji = L_i - (L_i - L_j) * exp( - r_B * (tL(tL(:,1) >= t_j,1) - t_j));
tL = [L_bj; L_ji]/ del_M; % cm, physical length

% time - wet weight
[tau_j, tau_p, tau_b, l_j, l_p, l_b, l_i, rho_j, rho_B] = get_tj(pars_tj, f_tWw);
r_B = TC_tWw * rho_B * k_M; r_j = TC_tWw * rho_j * k_M; t_j = (tau_j - tau_b)/ k_M/ TC_tWw;
L_b = L_m * l_b;  L_j = L_m * l_j; L_i = L_m * l_i;
L_bj = L_b * exp(tWw(tWw(:,1) < t_j,1) * r_j/ 3);
L_ji = L_i - (L_i - L_j) * exp( - r_B * (tWw(tWw(:,1) >= t_j,1) - t_j));
tWw = [L_bj; L_ji].^3 * (1 + f_tWw * ome); % g, wet weight

% pack to output
prdData.LWw = LWw;
prdData.tL = tL;
prdData.tWw = tWw;

