function [data, auxData, metaData, txtData, weights] = mydata_Ciliata_septentrionalis
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Gadiformes';
metaData.family     = 'Lotidae';
metaData.species    = 'Ciliata_septentrionalis';
metaData.species_en = 'Northern rockling';

metaData.ecoCode.climate = {'MC'};
metaData.ecoCode.ecozone = {'MANE'};
metaData.ecoCode.habitat = {'jiMi','0jMcp'};
metaData.ecoCode.embryo  = {'Mp'}; 
metaData.ecoCode.migrate = {'Mo'};
metaData.ecoCode.food    = {'biHa','biCiw','biCim','biCid','biCik','biCvf'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(13); % K, body temp

metaData.data_0     = {'am';'Lp';'Li';'Wwb';'Wwp';'Wwi';'GSI'};
metaData.data_1     = {'t-L'};

metaData.COMPLETE   = 2.5; % using criteria of LikaKear2011

metaData.author   = {'Bas Kooijman'};        
metaData.date_subm = [2024 09 30];                           
metaData.email    = {'bas.kooijman@vu.nl'};                 
metaData.address  = {'VU University, Amsterdam'}; 

metaData.curator     = {'Dina Lika'};
metaData.email_cur   = {'lika@uoc.gr'}; 
metaData.date_acc    = [2024 09 30];

%% set zero-variate data
data.am = 4*365; units.am = 'd'; label.am = 'life span'; bibkey.am = 'ClarGard1977';
  temp.am = C2K(13); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lp = 6.2; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = 'fishbase';
data.Li = 20; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = 'fishbase';

data.Wwb = 3e-4;    units.Wwb = 'g';   label.Wwb = 'wet weight at birth';     bibkey.Wwb = 'ClarGard1977';
  comment.Wwb = 'based on egg diameter of 0.83 mm: pi/6*0.083^3';
data.Wwp = 1;  units.Wwp = 'g'; label.Wwp = 'wet weight at puberty';     bibkey.Wwp = 'fishbase';
  comment.Wwp = 'based on 0.00347*Lp^3.11, see F1';
data.Wwi = 38.6;  units.Wwi = 'g'; label.Wwi = 'ultimate wet weight';     bibkey.Wwi = 'fishbase';
  comment.Wwi = 'based on 0.00347*Li^3.11, see F1';

data.GSI  = 0.10;   units.GSI  = '-'; label.GSI  = 'gonado somatic index';   bibkey.GSI  = 'ClarGard1977';   
  temp.GSI = C2K(28.5);  units.temp.GSI = 'K'; label.temp.GSI = 'temperature';

%% set uni-variate data

% time - length
data.tL_fm = [ ... 
    0  6.210  7.176
    1  8.037  9.540
    2 10.450 10.40];
data.tL_fm(:,1) = 365 * (1.5 + data.tL_fm(:,1)); % convert yr to d 
units.tL_fm = {'d', 'cm'}; label.tL_fm = {'time', 'length'};
temp.tL_fm = C2K(13); units.temp.tL_fm = 'K'; label.temp.tL_fm = 'temperature';
bibkey.tL_fm = 'ClarGard1977'; treat.tL_fm = {1 {'females','males'}};

%% set weights for all real data
weights = setweights(data, []);
weights.tL_fm = 10 * weights.tL_fm;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
auxData.treat = treat;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

% %% Group plots
% set1 = {'tL_f','tL_m'}; subtitle1 = {'Data for females, males'};
% metaData.grp.sets = {set1};
% metaData.grp.subtitle = {subtitle1};

%% Discussion points
D1  = 'males are supposed to differ from females by {p_Am} only';
D2 = 'I had to add 1 yr to tL data to arrive at a natural fit';
metaData.discussion = struct('D1',D1, 'D2',D2);

%% Links
metaData.links.id_CoL = 'VBRJ'; % Cat of Life
metaData.links.id_ITIS = '164780'; % ITIS
metaData.links.id_EoL = '46564447'; % Ency of Life
metaData.links.id_Wiki = 'Ciliata_septentrionalis'; % Wikipedia
metaData.links.id_ADW = 'Ciliata_septentrionalis'; % Anim Div. Web
metaData.links.id_Taxo = '44301'; % Taxonomicon
metaData.links.id_WoRMS = '126448';
metaData.links.id_fishbase = 'Ciliata_septentrionalis';

%% References
bibkey = 'Wiki'; type = 'Misc'; bib = [...
'howpublished = {\url{http://en.wikipedia.org/wiki/Ciliata_septentrionalis}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'ClarGard1977'; type = 'article'; bib = [ ...
'doi = {10.1017/s0025315400025194}, ' ...
'author = {Claridge, P. N. and Gardner, D. C.}, ' ... 
'title = {The biology of the northern rockling, \emph{Ciliata septentrionalis}, in the {S}evern {E}stuary and {B}ristol {C}hannel}, ' ... 
'journal = {Journal of the Marine Biological Association of the United Kingdom}, ' ... 
'year = {1977}, ' ... 
'volume = {57(03)}, '...
'pages = {839}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'fishbase'; type = 'Misc'; bib = [...
'howpublished = {\url{http://www.fishbase.org/summary/Ciliata_septentrionalis.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];

