function [data, auxData, metaData, txtData, weights] = mydata_Pterois_miles
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Scorpaeniformes';
metaData.family     = 'Scorpaenidae';
metaData.species    = 'Pterois_miles';
metaData.species_en = 'Devil firefish';

metaData.ecoCode.climate = {'MA'};
metaData.ecoCode.ecozone = {'MI'};
metaData.ecoCode.habitat = {'biMr','biMb'};
metaData.ecoCode.embryo  = {'Mp'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biCi','jiCvf'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'A'};

metaData.T_typical  = C2K(27.6); % K, body temp

metaData.data_0     = {'am','Lh','Lp','Li','Wwi'};
metaData.data_1     = {'LWw','tL', 'L-W', 'L-N', 'W-N', 'JOT'};

metaData.COMPLETE   = 3; % using criteria of LikaKear2011

metaData.author   = {'Orestis Stavrakidis-Zachou','Evridiki Klagkou','Eleni Livanou','Dina Lika'};    
metaData.date_subm = [2024 12 16];              
metaData.email    = {'lika@uoc.gr'};            
metaData.address  = {'University of Crete, UoC'};   

metaData.curator    = {'Bas Kooijman'};
metaData.email_cur  = {'bas.kooijman@vu.nl'};
metaData.date_acc   = [2024 12 16];

%% set zero-variate data
data.am = 15*365; units.am = 'd'; label.am = 'life span'; bibkey.am = 'MorrAkin2008';
  temp.am = C2K(26); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lh = 0.015; units.Lh = 'cm'; label.Lh = 'length at hatch'; bibkey.Lh = 'MorrAkin2008';
data.Lp = 19; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = 'GardFraz2015';
data.Li = 43; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = 'bioweb';

data.Wwi = 1100; units.Wwi = 'g'; label.Wwi = 'ultimate wet weight'; bibkey.Wwi = 'bioweb';
  comment.Wwi = 'http://bioweb.uwlax.edu/bio203/s2013/belmore_luca/facts.htm';

%% set uni-variate data

% length-weight
data.LWw = [ ... 
  7.7 7.6
  8.7 9.1
  10.3 7.7
  12.1 20.9
  13.4 29.8
  14 29.8
  14.4 27.6
  15 56.8
  15.3 40
  15.5 31
  15.5 28.8
  15.8 52.3
  16 38.9
  16.5 110
  16.7 44.9
  16.7 56.5
  16.9 56.5
  17 71.1
  17.2 59.5
  17.4 69.2
  17.5 84.7
  17.9 54.6
  17.9 82.8
  18.1 68.2
  18.3 206.2
  18.4 79.9
  18.6 73.1
  18.9 97.4
  19 109.1
  19.1 73.1
  19.1 86.7
  19.2 198.5
  19.5 78
  19.5 89.7
  19.7 103.3
  19.8 94.5
  19.8 112
  19.9 126.6
  20 77.1
  20 91.6
  20.1 91.6
  20.2 35.3
  20.2 112
  20.2 131.5
  20.2 143.1
  20.4 127.6
  20.5 117.9
  20.6 99.4
  20.7 108.2
  20.8 122.7
  20.9 139.3
  20.9 116
  20.9 117.9
  21 92.6
  21.1 132.5
  21.1 121.8
  21.4 139.3
  21.4 116.9
  21.4 128.6
  21.6 101.4
  21.6 161.6
  21.7 128.6
  21.7 143.2
  21.9 180.1
  22 155.8
  22.2 51.9
  22.2 124.7
  22.2 127.7
  22.2 156.8
  22.2 170.4
  22.3 185
  22.4 148.1
  22.5 119.9
  22.5 132.5
  22.5 164.6
  22.6 158.8
  22.6 179.2
  22.6 192.8
  22.7 147.1
  22.8 141.3
  22.8 202.5
  22.9 105.3
  22.9 175.3
  23 167.5
  23 186
  23 215.1
  23.1 150
  23.2 162.7
  23.2 217.1
  23.3 188.9
  23.3 176.3
  23.4 130.6
  23.4 154.9
  23.5 173.4
  23.5 194.7
  23.5 207.4
  23.6 184.1
  23.6 214.2
  23.7 223.9
  23.8 194.7
  23.8 250.1
  23.9 180.2
  23.9 169.5
  23.9 206.4
  23.9 188
  24 232.6
  24.1 185
  24.1 199.6
  24.2 200.6
  24.3 156.9
  24.3 207.4
  24.3 217.1
  24.4 134.5
  24.4 248.2
  24.5 183.1
  24.5 225.9
  24.6 181.2
  24.6 196.7
  24.6 242.4
  24.7 200.6
  24.7 210.3
  24.7 223.9
  24.7 231.7
  24.7 270.6
  24.8 239.5
  24.8 253.1
  25 163.7
  25 209.4
  25 221
  25.1 184.1
  25.1 237.5
  25.1 262.8
  25.2 195.8
  25.2 231.7
  25.2 278.3
  25.3 188
  25.3 218.1
  25.3 224.9
  25.4 234.6
  25.5 213.3
  25.5 256
  25.6 240.5
  25.7 245.3
  25.7 261.8
  25.7 298.8
  25.8 249.2
  25.9 229.8
  26 167.6
  26 218.1
  26 240.5
  26 286.1
  26 339.6
  26 252.1
  26 264.8
  26.1 153.1
  26.2 297.8
  26.2 253.1
  26.3 265.8
  26.5 270.6
  26.6 301.7
  26.6 280.3
  26.7 272.6
  26.7 258
  26.8 261.9
  26.9 278.4
  26.9 283.3
  27 246.4
  27.2 239.6
  27.2 325
  27.4 342.5
  27.4 404.7
  27.5 294
  27.5 209.5
  27.6 288.1
  27.6 309.5
  27.6 319.2
  27.7 277.5
  28 311.5
  28 348.4
  28.1 322.2
  28.4 306.6
  28.4 324.1
  28.4 387.3
  28.6 346.5
  28.7 354.2
  28.9 358.1
  29.1 318.3
  29.1 352.3
  29.3 363
  29.7 407.7
  29.9 392.2
  30.1 437.8
  30.2 419.4
  30.3 364
  30.6 531.1
  30.8 554.4
  31 420.4
  31 480.6
  31.4 263
  32 393.2
  32 437.9
  32 526.3
  32 585.6
  32.1 497.2
  32.4 588.5
  32.5 568.1
  33 403
  33.1 311.7
  33.1 465.2
  33.9 668.2
  34.1 541.9
  34.7 367.1
  34.7 633.3
  35 533.2
  36 755.7
  36.8 837.4
  36.9 851
  37.1 757.7];
units.LWw = {'cm', 'g'}; label.LWw = {'length', 'wet weight'};
bibkey.LWw = 'SavvaChar2019';

% time - length
data.tL = [ ... 
  182.5 15.86
  178.85 18.33
  361.35 15.18
  365 21.12
  361.35 21.91
  547.5 16.47
  722.7 17.08
  543.85 20.24
  543.85 20.93
  540.2 21.62
  540.2 22.22
  540.2 22.91
  540.2 24.3
  547.5 24.79
  543.85 25.48
  540.2 25.98
  540.2 26.57
  543.85 28.45
  540.2 29.05
  540.2 29.25
  547.5 32.91
  730 24.11
  730 24.7
  722.7 25.2
  726.35 25.99
  730 27.38
  730 28.27
  726.35 28.86
  722.7 36.88
  908.85 23.62
  908.85 24.61
  905.2 26.89
  905.2 27.58
  905.2 28.08
  908.85 29.07
  905.2 30.65
  905.2 31.94
  1091.35 25.71
  1095 30.27
  1095 32.05
  1095 32.45
  1273.85 33.55
  1270.2 34.64
  1456.35 34.55
  1452.7 30.98];
units.tL = {'d', 'cm'}; label.tL = {'time', 'length'};
for i=2:size(data.tL,1); if data.tL(i,1)<=data.tL(i-1,1); data.tL(i,1)=data.tL(i-1,1)+1e-3;end;end
temp.tL = C2K(22.5); units.temp.tL = 'K'; label.temp.tL = 'temperature';
bibkey.tL = 'SavvaChar2019';
comment.tL = 'temp averaged over the year';
%
data.tL1 = [ ...  % timesince birth (d), body length (mm)
    0.94	0.73
    3.96	2.32
    5.02	2.00
    6.07	1.52
    6.09	3.11
    7.06	2.92
    7.05	2.50
    7.05	2.22
    7.05	2.03
    7.98	2.06
    8.03	2.50
    8.03	2.73
    8.03	2.89
    8.96	2.72
    9.09	3.17
    10.02	2.91
    10.02	3.07
    10.07	3.61
    10.07	3.84
    11.04	3.45
    11.01	4.28
    11.01	5.02
    11.07	5.91
    11.08	7.09
    12.08	5.81
    12.08	5.30
    12.07	4.89
    12.07	4.60
    13.00	4.63
    13.01	5.33
    13.01	5.55
    13.02	6.45
    13.11	6.77
    14.09	3.64
    14.10	3.83
    14.07	5.42
    14.07	5.55
    14.07	5.81
    14.07	5.87
    14.08	6.64
    14.08	6.76
    14.08	6.99
    14.08	10.24
    15.12	8.58
    15.12	8.36
    15.20	7.62
    15.10	7.14
    15.09	5.68
    15.98	6.19
    17.09	7.17
    17.10	7.65
    17.16	9.15];
data.tL1(:,2) = data.tL1(:,2)/10;  % convert mm to cm
for i=2:size(data.tL1,1); if data.tL1(i,1)<=data.tL1(i-1,1); data.tL1(i,1)=data.tL1(i-1,1)+1e-3;end;end
units.tL1 = {'d', 'cm'}; label.tL1 = {'time', 'length'};
temp.tL1 = C2K(27.4); units.temp.tL1 = 'K'; label.temp.tL1 = 'temperature';
bibkey.tL1 = 'MostMalc2020';
comment.tL1 = 'average temperature at the time of the study';

% length-reproduction rate
data.LR = [... total length (cm), reproduction rate (#/9d)
    20.45	4700.85
    21.02	1709.40
    20.71	9401.71
    21.08	6196.58
    21.53	5128.20
    21.79	13675.21
    22.04	9615.38
    22.80	11324.79
    23.11	10042.73
    24.38	8547.01
    24.70	11538.46
    24.95	14102.56
    24.59	24358.97
    24.59	26068.38
    26.22	10042.73
    25.61	31837.61
    26.75	32905.98
    28.39	25213.68
    28.21	35683.76
    33.28	41666.67];
data.LR(:,2) = data.LR(:,2)/9; % convert 9 d to d
units.LR  = {'cm', '#/d'};  label.LR = {'total length', 'reproduction rate'};  
temp.LR = C2K(26.5); units.temp.LR= 'K'; label.temp.LR = 'temperature';
bibkey.LR = 'GardFraz2015';
comment.LR = 'temp is an average of the area and time, eggs collected in a range of 9d';

% weight-reproduction rate
data.WR = [... total weight (g), reproduction rate (#/9d)
    104.33	4935.63
    118.67	2145.93
    109.30	9871.24
    120.56	11373.40
    131.58	4935.63
    141.25	6652.36
    170.33	13948.50
    179.82	10300.43
    191.10	12231.77
    194.22	9442.07
    240.71	10085.84
    213.62	14806.87
    199.52	24678.11
    225.22	26609.44
    230.18	31545.06
    265.48	32618.03
    281.62	36266.10
    308.52	25536.48
    462.89	41845.49];
data.WR(:,2) = data.WR(:,2)/9; % convert 9 d to d
units.WR  = {'g', '#/d'};  label.WR = {'total weight', 'reproduction rate'};  
temp.WR = C2K(26.5); units.temp.WR = 'K'; label.temp.WR = 'temperature';
bibkey.WR = 'GardFraz2015';

% temperature-O2 consumption
data.JOT = [... temperature (C), metabolic scope (mg O2/kg/h)
   26	69.6
   32   118.4];
units.JOT = {'C','mg O_2/h.kg'}; label.JOT = {'temperature','specific O_2 consumption'};
bibkey.JOT = 'SteeLeeu2019';

%% set weights for all real data
weights = setweights(data, []);
weights.tL = 3 * weights.tL;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Discussion points
D1  = 'males are assumed not to differ from females';
metaData.discussion = struct('D1',D1);

%% Links
metaData.links.id_CoL = '4PWV4'; % Cat of Life
metaData.links.id_EoL = '46568063'; % Ency of Life
metaData.links.id_Wiki = 'Pterois_miles'; % Wikipedia
metaData.links.id_ADW = 'Pterois_miles'; % Anim Div. Web
metaData.links.id_Taxo = '105785'; % Taxonomicon
metaData.links.id_WoRMS = '218077'; % WoRMS
metaData.links.id_fishbase = 'Pterois-miles'; % fishbase

%% References
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'MorrAkin2008'; type = 'article'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Morris, J. and Akins, J.L. and Barse, A. and Cerino, D. and  Freshwater, D.W. and Green, S.J. and Muñoz, R.C. and Paris, C. and Whitfield, P.E.}, ' ...
'year = {2008}, ' ...
'title  = {Biology and Ecology of the Invasive Lionfishes, \emph{Pterois miles} and \emph{Pterois volitans}}, ' ...
'journal = {Proceedings of the Gulf and Caribbean Fisheries Institute}, ' ...
'pages = {409-414}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'GardFraz2015'; type = 'article'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'doi = {10.3389/fmars.2015.00007}, ' ...
'author = {Gardner, P. and Frazer, T. and Jacoby, C. and Yanong, R.}, ' ...
'year = {2015}, ' ...
'title  = {Reproductive biology of invasive lionfish (\emph{Pterois} spp.)}, ' ...
'journal = {Original Research Article}, ' ...
'volume = {2},'...
'pages = {1-10}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'bioweb'; type = 'misc'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {bioweb}, ' ...
'title  = {http://bioweb.uwlax.edu/bio203/s2013/belmore_luca/facts.htm}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'SavvaChar2019'; type = 'article'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'doi = {10.1111/jfb.14340}, ' ...
'author = {Savva, I. and Chartosia, N. and Antoniou, C. and Kleitou, P. and Georgiou, A. and Stern, N. and Hadjioannou, L. and Jimenez, C. and Andreou, V. and M. Hall-Spencer, J. and Kletou, D.}, ' ...
'year = {2019}, ' ...
'title  = {They are here to stay: the biology and ecology of lionfish (\emph{Pterois miles}) in the {M}editerranean {S}ea}, ' ...
'journal = {J. Fish Biol.}, ' ...
'volume = {97},'...
'pages = {148-162}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'SteeLeeu2019'; type = 'article'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'doi = {10.1242/jeb.209437}, ' ...
'author = {Steell C. and van Leeuwen, T. and Brownscombe, J. and Cooke, S. and Eliason, E.}, ' ...
'year = {2019}, ' ...
'title  = {An appetite for invasion: digestive physiology, thermal performance and food intake in lionfish (\emph{Pterois} spp.)}, ' ...
'journal = {J. Exp. Biol.}, ' ...
'volume = {222},'...
'pages = {1-12}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'MostMalc2020'; type = 'article'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'doi = {10.1371/journal.pone.0243138}, ' ...
'author = {Mostowy, J. and Malca, E. and Rasmuson, L. and Vasquez-Yeomans, L. and Gerard, T. and Sosa Cordero, E. and Carrillo, L. and Lamkin, J.}, ' ...
'year = {2020}, ' ...
'title  = {Early life ecology of the invasive lionfish (\emph{Pterois} spp.) in the western {A}tlantic}, ' ...
'journal = {PLOS One}, ' ...
'volume = {15}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
