function [data, auxData, metaData, txtData, weights] = mydata_Pedioplanis_husabensis
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Sarcopterygii';
metaData.order      = 'Squamata';
metaData.family     = 'Lacertidae';
metaData.species    = 'Pedioplanis_husabensis';
metaData.species_en = 'Husab Sand Lizard';

metaData.ecoCode.climate = {'BWh'};
metaData.ecoCode.ecozone = {'TPa'};
metaData.ecoCode.habitat = {'jpTd'};
metaData.ecoCode.embryo  = {'Tnt'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'jpCi'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(34); % K, body temp

metaData.data_0     = {'am','Lb','Li','Wwi','Ri'};
metaData.data_1     = {'L-Ww','JC-Ww'};

metaData.COMPLETE   = 1; % using criteria of LikaKear2011

metaData.author     = {'Urban Dajcman'};
metaData.date_subm  = [2023 6 29];
metaData.email      = {'urban.dajcman@nib.si'};
metaData.address    = {'Vecna pot 111, Ljubljana, Slovenija'};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight@tecnico.ulisboa.pt'};
metaData.date_acc   = [2023 7 04];

%% set zero-variate data
data.am = 1825; units.am = 'd'; label.am = 'life span'; bibkey.am = 'SchaFeld2015';
  temp.am = C2K(34); units.temp.am = 'K'; label.temp.am = 'temperature';
  comment.am = 'time based on Pedioplanis lineoocellata, temperature based on minimum field temperature ';

data.Lb  = 2;  units.Lb  = 'cm';  label.Lb  = 'SVL at hatching'; bibkey.Lb  = 'Bran1998'; 
  comment.Lb ='SVL  based on similar sized related species'; 
data.Li = 5.6; units.Li = 'cm'; label.Li = 'ultimate SVL length for females'; bibkey.Li = 'MurrFull2014';
  comment.Li = 'Data for females';
data.Lim  = 6.123;    units.Lim  = 'cm'; label.Lim  = 'ultimate SVL for males';   bibkey.Lim  = 'Conradie2012';  
  comment.Lim = 'Short note on extreme length male';
    
data.Wwi = 5.37;  units.Wwi = 'g';   label.Wwi = 'ultimate wet weight';       bibkey.Wwi = 'MeirAvil2020';
  comment.Wwi = 'Taken from supplementary data' ;
  
data.Ri = 0.00410959; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = 'MeirAvil2020';
  temp.Ri = C2K(34); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  
%% set univariate data

% length-weight
data.LW_f = [ ... % SVL (cm), wet weight (g)
43.99624565370422, 1.599447513812155
43.97512745579044, 1.9088397790055254
43.97572473815568, 1.9990791896869249
45.9693679472685, 2.2053406998158382
45.991766035964936, 2.0893186003683244
46.98995285735617, 2.3987108655616947
47.01179632671346, 2.1988950276243098
47.01115638132213, 2.102209944751382
47.98408669126901, 2.095764272559853
48.02969346615755, 1.9861878453038675
48.02849890142708, 1.8057090239410685
48.979543078990595, 1.9926335174953964
49.0286055589923, 2.405156537753223
49.00735937200026, 2.695211786372008
50.003498368139255, 2.695211786372008
50.02474455513129, 2.405156537753223
49.97781522643401, 2.3149171270718236
50.9499776019113, 2.1924493554327813
50.95206809018964, 2.50828729281768
51.92636361697135, 2.708103130755065
52.01693722135711, 2.392265193370166
52.98986753130399, 2.3858195211786377
52.96759743168583, 2.521178637200737
53.038290065914374, 2.7016574585635365
53.03884468525352, 2.7854511970534075
52.970029224172876, 2.888581952117864
55.01196697881781, 3.391344383057091
55.01136969645257, 3.301104972375691
55.008809914887266, 2.9143646408839783
55.03052539516628, 2.695211786372008
55.02980012372278, 2.5856353591160226
55.981057616416734, 2.804788213627993
55.98502527784296, 3.404235727440148
56.010068474156874, 3.687845303867404
53.96697881780755, 3.0110497237569067
54.03502634441861, 2.791896869244936
53.96505898163357, 2.720994475138122
53.98681712493867, 2.50828729281768
53.98617717954735, 2.411602209944752];
data.LW_f(:,1) = data.LW_f(:,1) /10 ; % convert mm to cm
units.LW_f  = {'cm', 'g'};  label.LW_f = {'SVL', 'wet weight', 'female'};  
bibkey.LW_f = 'MurrFull2014';
% males
data.LW_m = [ ... % SVL (cm), wet weight (g)
44.02333667527038, 2.1924493554327813
44.069156765289364, 2.1151012891344383
44.996309648243354, 2.1924493554327813
44.99246997589539, 1.612338858195212
48.03255188890548, 2.4180478821362805
49.00407431899145, 2.1988950276243098
48.984961283303825, 2.811233885819522
50.02811493419228, 2.9143646408839783
50.07227116619382, 2.5856353591160226
50.071801872906846, 2.5147329650092085
51.00637812240022, 3.7136279926335183
51.02613110347917, 3.197974217311234
51.09306939141194, 2.811233885819522
50.999680027304336, 2.7016574585635365
50.99767486507818, 2.3987108655616947
52.02427526184432, 3.500920810313076
52.02367797947909, 3.4106813996316765
52.02295270803558, 3.301104972375691
52.02158749120075, 3.0948434622467778
53.06819684720237, 3.7200736648250468
53.019816975618085, 3.4106813996316765
53.01909170417458, 3.301104972375691
52.99511508351287, 3.178637200736649
54.062842637428275, 3.4944751381215475
54.01595597175708, 3.4106813996316765
54.037116832696945, 3.1077348066298347
53.98933424347789, 2.888581952117864
54.992853943130186, 4.003683241252302
54.99089144393012, 3.70718232044199
55.03654088184475, 3.604051565377533
54.989568890121376, 3.5073664825046045
54.98632650013866, 3.017495395948435
56.03549563770558, 4.029465930018417
56.01194564730476, 3.97145488029466
56.01147635401779, 3.900552486187846
56.01075108257429, 3.790976058931861
57.00825529554811, 3.997237569060774
57.00693274173938, 3.7974217311233893
56.9832120992342, 3.7136279926335183
57.0282215917575, 3.513812154696133
58.00238912946095, 3.6942909760589324
58.97881780754709, 4.2163904235727445];
data.LW_m(:,1) = data.LW_m(:,1) /10 ; % convert mm to cm
units.LW_m  = {'cm', 'g'};  label.LW_m = {'SVL', 'wet weight', 'male'};  
bibkey.LW_m = 'MurrFull2014';

% weight-CO2 production
data.WJC = [... % wet weight (g), CO2 prod (ml/min)
2.1	2.2	2.2	2.2	2.4	2.5	2.5	2.6	2.8	2.8	2.9	3.2	3.5	3.7	4	4	4.2
0.0049	0.005133333	0.005133333	0.0044	0.0056	0.009583333	0.006666667	0.0052	0.0112	0.007466667	0.005316667	0.014933333	0.015166667	0.012333333	0.014666667	0.015333333	0.0105
]'; % vCO2 ml/min
units.WJC  = {'g', 'ml/min'};  label.WJC = {'wet weight', 'CO_2 production', '37 C'};  
temp.WJC  = C2K(37);  units.temp.WJC = 'C'; label.temp.WJC = 'temperature';
bibkey.WJC = 'MurrFull2014';

%% set weights for all real data
weights = setweights(data, []);
weights.Li = 3 * weights.Li;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Group plots
set1 = {'LW_f','LW_m'}; subtitle1 = {'Data for females, males'};
metaData.grp.sets = {set1};
metaData.grp.subtitle = {subtitle1};

%% Discussion points
D1 = 'Males are assumed to differ from females by {p_Am} only';
metaData.discussion = struct('D1',D1);

%% Links
metaData.links.id_CoL = '75XTV'; % Cat of Life
metaData.links.id_ITIS = '1155392'; % ITIS
metaData.links.id_EoL = '791186'; % Ency of Life
metaData.links.id_Wiki = 'Pedioplanis_husabensis'; % Wikipedia
metaData.links.id_ADW = 'Pedioplanis_husabensis'; % ADW
metaData.links.id_Taxo = '642659'; % Taxonomicon
metaData.links.id_WoRMS = ''; % WoRMS
metaData.links.id_ReptileDB = 'genus=Pedioplanis&species=husabensis'; % ReptileDB
metaData.links.id_AnAge = ''; % AnAge

%% References
bibkey = 'Conradie2012'; type = 'article'; bib = [ ...   
'author = {Werner Conradie}, ' ...
'year = {2012}, ' ...
'title  = {Natural History Note, \emph{Pedioplanis husabensis}}, ' ...
'journal = {The HERPETOLOGICAL BULLETIN 120, BRITISH HERPETOLOGICAL SOCIETY}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'SchaFeld2015'; type = 'article'; bib = [ ...
'doi = {10.1111/geb.12244}, ' ...   
'author = {Inon Scharf and Anat Feldman and Maria Novosolov and Daniel Pincheira-Donoso and Indraneil Das and Monika B\"{o}hm and Peter Uetz and Omar Torres-Carvajal and  Aaron Bauer and Uri Roll and Shai Meiri}, ' ...
'year = {2015}, ' ...
'title  = {Late bloomers and baby boomers: ecological drivers of longevity in squamates and the tuatara}, ' ...
'journal = {Global Ecology and Biogeography}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'MeirAvil2020'; type = 'article'; bib = [ ...
'doi = {10.1111/geb.13124}, ' ...   
'author = {Shai Meiri and Luciano Avila and Aaron M. Bauer and David G. Chapple and Indraneil Das and Tiffany M. Doan and Paul Doughty and Ryan Ellis and Lee Grismer and Fred Kraus and Mariana Morando and Paul Oliver and Daniel Pincheira-Donoso and Marco Antonio Ribeiro-Junior and Glenn Shea and Omar Torres-Carvajal and Alex Slavenko and Uri Roll}, ' ...
'year = {2020}, ' ...
'title  = {The global diversity and distribution of lizard clutch sizes}, ' ...
'journal = {Global Ecology and Biogeography}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'MurrFull2014'; type = 'article'; bib = [ ...
'doi = {10.1139/cjz-2014-0086}, ' ...
'author = {Ian W. Murray and Andrea Fuller and Hilary M. Lease and Duncan Mitchell and Blair O. Wolf and Robyn S. Hetem}, ' ...
'year = {2014}, ' ...
'title  = {The actively foraging desert lizard \emph{Pedioplanis husabensis} ({H}usab Sand Lizard) behaviorally optimizes its energetic economy}, ' ...
'journal = {Canadian Journal of Zoology}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Bran1998'; type = 'Book'; bib = [ ...
'author = {Bill Branch}, ' ...
'year = {1998}, ' ...
'title  = {Field Guide to the Snakes and Other Reptiles of {S}outhern {A}frica}, ' ...
'publisher = {Ralph Curtis Publishing}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
