function [data, auxData, metaData, txtData, weights] = mydata_Ciliata_mustela
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Gadiformes';
metaData.family     = 'Lotidae';
metaData.species    = 'Ciliata_mustela';
metaData.species_en = 'Five-bear rockling';

metaData.ecoCode.climate = {'MC'};
metaData.ecoCode.ecozone = {'MANE'};
metaData.ecoCode.habitat = {'jiMi','0jMcp'};
metaData.ecoCode.embryo  = {'Mp'}; 
metaData.ecoCode.migrate = {'Mo'};
metaData.ecoCode.food    = {'biHa','biCiw','biCim','biCid','biCik','biCvf'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(13); % K, body temp

metaData.data_0     = {'ap';'am';'Lp';'Li';'Wwb';'Ri'};
metaData.data_1     = {'L-Ww';'t-L'};

metaData.COMPLETE   = 2.5; % using criteria of LikaKear2011

metaData.author     = {'Bass Dye'};
metaData.date_subm  = [2021 5 12];
metaData.email      = {'bass.dye@nioz.nl'};
metaData.address    = {'NIOZ Royal Netherlands Institute for Sea Research'};

metaData.author_mod_1   = {'Bas Kooijman'};    
metaData.date_mod_1     = [2023 04 03];              
metaData.email_mod_1    = {'bas.kooijman@vu.nl'};            
metaData.address_mod_1  = {'VU University, Amsterdam'};   

metaData.curator     = {'Starrlight Augustine'};
metaData.email_cur   = {'starrlight@tecnico.ulisboa.pt'}; 
metaData.date_acc    = [2023 04 03];

%% set zero-variate data
data.tp = 365; units.tp = 'd'; label.tp = 'time since birth at puberty'; bibkey.tp = 'CoheInad1990';
  temp.tp = C2K(13); units.temp.tp = 'K'; label.temp.tp = 'temperature';
data.am = 1460; units.am = 'd'; label.am = 'life span'; bibkey.am = 'Smie1992';
  temp.am = C2K(13); units.temp.am = 'K'; label.temp.am = 'temperature';
  comment.am = 'CoheInad1990 - 3 years (1095 days)';

data.Lp = 14; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = 'CoheInad1990';
  comment.Lp = 'Smie1992 - 13.4-16.0; BadsSain1978 - 14.2-18.3 (unsexed)';
data.Lpm = 12; units.Lpm = 'cm'; label.Lpm = 'length at puberty for males'; bibkey.Lpm = 'CoheInad1990';
  comment.Lpm = 'CoheInad1990 - 11-13; Smiet1992 - 14.9';
data.Li = 25; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = 'CoheInad1990';

data.Wwb = 3e-4;    units.Wwb = 'g';   label.Wwb = 'wet weight at birth';     bibkey.Wwb = 'CoheInad1990';
  comment.Wwb = 'based on egg diameter of 0.83 mm: pi/6*0.083^3';

data.Ri = 82.19; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = 'CoheInad1990';
  temp.Ri = C2K(13); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = '30000 eggs in 1 reprod. cyce divided by 365 days; 9,000-30,000 eggs per female per year';

%% set uni-variate data
% length-weight
data.LWw = [ ... 
  1 0.00616595
  3 0.186631
  4 0.455821
  5 0.911177
  6 1.60465
  7 2.58931
  8.33333 4.44858
  9.47619 6.62935
  10.619 9.43995
  11.7619 12.9647
  12.9048 17.2889
  14.0476 22.4988
  15.1905 28.6812
  16.3333 35.924
  17.4762 44.3154
  18.619 53.9446
  19.7619 64.9012
  20.9048 77.2754
  22.0476 91.158
  23.1905 106.64
  1 0.00485289
  3 0.146887
  4 0.358752
  5 0.717138
  6 1.26294
  7 2.03791
  8.33333 3.50124
  9.47619 5.21761
  10.619 7.42967
  11.7619 10.2038
  12.9048 13.6072
  14.0476 17.7076
  15.1905 22.5734
  16.3333 28.2738
  17.4762 34.8783
  18.619 42.4569
  19.7619 51.0802
  20.9048 60.8193
  22.0476 71.7455
  23.1905 83.9308];
units.LWw = {'cm', 'g'}; label.LWw = {'length', 'wet weight'};
bibkey.LWw = {'BadsSain1978'};
comment.LWw = 'unsexed';

% time-length
data.tL_f = [ ... 
  365 11.7
  730 16.8
  1095 19.9
  1460 23.2];
units.tL_f = {'d', 'cm'}; label.tL_f = {'time', 'length', 'female'};
temp.tL_f = C2K(13); units.temp.tL_f = 'K'; label.temp.tL_f = 'temperature';
bibkey.tL_f = {'Smie1992'};
comment.tL_f = 'data for females, Table 2';
%
data.tL_m = [ ... 
  365 11.2
  730 13.5
  1095 17.8];
units.tL_m = {'d', 'cm'}; label.tL_m = {'time', 'length', 'male'};
temp.tL_m = C2K(13); units.temp.tL_m = 'K'; label.temp.tL_m = 'temperature';
bibkey.tL_m = {'Smie1992'};
comment.tL_m = 'data for males, Table 2';

%% set weights for all real data
weights = setweights(data, []);
weights.tL_f = 5 * weights.tL_f;
weights.tL_m = 5 * weights.tL_m;
weights.Li = 3 * weights.Li;
weights.Lp = 3 * weights.Lp;
weights.Lpm = 3 * weights.Lpm;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Group plots
set1 = {'tL_f','tL_m'}; subtitle1 = {'Data for females, males'};
metaData.grp.sets = {set1};
metaData.grp.subtitle = {subtitle1};

%% Discussion points
D1 = 'males are supposed to differ from females by {p_Am} and E_Hp only';
D2  = 'Typical body temp in *C (T_typical) was chosen to be 13*C based on ongoing Ciliata mustela experimental temperature preference work by Bass Dye';
D3  = 'am (life span) 0-variate data chosen to be 4 years (1460 days) because Smie1992 found 1 fish at 4 years old. CoheInad1990 said max age 3 years (1065 days)';
D4  = 'Lpm and Lp uses values from CoheInad1990 although other values available from Smie1992 and BadsSain1978';
D5 = 'mod_1: males have equal state variables at b, compared to females';
metaData.discussion = struct('D1',D1, 'D2',D2, 'D3',D3, 'D4',D4, 'D5',D5);

%% Links
metaData.links.id_CoL = 'VBRH'; % Cat of Life
metaData.links.id_ITIS = '623023'; % ITIS
metaData.links.id_EoL = '46564446'; % Ency of Life
metaData.links.id_Wiki = 'Ciliata_mustela'; % Wikipedia
metaData.links.id_ADW = 'Ciliata_mustela'; % Anim Div. Web
metaData.links.id_Taxo = '44301'; % Taxonomicon
metaData.links.id_WoRMS = '126448';
metaData.links.id_fishbase = 'Ciliata-mustela';

%% References
bibkey = 'BadsSain1978'; type = 'article'; bib = [ ...
'author = {Badsha, KS and Sainsbury, M}, ' ... 
'title = {Aspects of the biology and heavy metal accumulation of \emph{Ciliata mustela}}, ' ... 
'journal = {Journal of Fish Biology}, ' ... 
'year = {1978}, ' ... 
'volume = {12}, ' ... 
'pages = {213--220}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'CoheInad1990'; type = 'book'; bib = [ ...
'author = {Cohen, Danuel M and Inada, Tadashi and Iwamoto, Tomio and Scialabba, Nadia and Whitehead, Peter James Palmer}, ' ... 
'title = {FAO species catalogue: vol. 10 gadiform fishes of the world (order gadiformes), an annotated and ilustrated catalogue of Cods. Hakes, grenadiers and other gadiform fishes known to date}, ' ... 
'publisher = {FOOD AND AGRICULTURE ORGANIZATION OF THE UNITED NATIONS}, ' ... 
'year = {1990}, ' ... 
'series = {125}, ' ... 
'volume = {10}, ' ... 
'isbn = {92-5-102890-7}, ' ... 
'howpublished = {\url{http://www.fao.org/3/t0243e/t0243e00.htm}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Smie1992'; type = 'article'; bib = [ ...
'author = {{Smietana, P}}, ' ... 
'title = {Assessment of the length growth rate of five-bearded rockling [\emph{Ciliata mustela} {L}.] of the {W}adden {S}ea origin}, ' ... 
'journal = {Acta Ichthyologica et Piscatoria}, ' ... 
'year = {1992}, ' ... 
'volume = {1}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

